fn test(n)
  case n of
    when 1 print "One"
    when 2 print "Two"
    when 3 print "Three"
    else print "Number not known"
  endcase
endfn

test(1)
test(2)
test(3)
test(0)

fn range(n)
  #print 0 < n < 10
  case true of
    when n = 10 print "Ten exactly"
    when 0 < n < 10 print "Under ten and above zero"
    when n > 10 print "Above ten"
    else print "Out of range"
  endcase
endfn

range(10)
range(1)
range(100)
range(-1)
