// Generated by Flexc++ V2.14.00 on Wed, 16 Aug 2023 12:53:43 +0100

#ifndef Loxer_H_INCLUDED_
#define Loxer_H_INCLUDED_

// $insert baseclass_h
#include "Loxerbase.h"

#include "../parser/Tokens.h"

// $insert classHead
class Loxer: public LoxerBase
{
    public:
        explicit Loxer(std::istream &in = std::cin, std::ostream &out = std::cout, bool keepCwd = true);

        Loxer(std::string const &infile, std::string const &outfile, bool keepCwd = true);
        
        // $insert lexFunctionDecl
        int lex();

    private:
        int lex_();
        int executeAction_(size_t ruleNr);

        void print();
        void preCode();     // re-implement this function for code that must 
                            // be exec'ed before the patternmatching starts

        void postCode(PostEnum_ type);    
                            // re-implement this function for code that must 
                            // be exec'ed after the rules's actions.
};

// $insert scannerConstructors
inline Loxer::Loxer(std::istream &in, std::ostream &out, bool keepCwd)
:
    LoxerBase(in, out, keepCwd)
{}

inline Loxer::Loxer(std::string const &infile, std::string const &outfile, bool keepCwd)
:
    LoxerBase(infile, outfile, keepCwd)
{}

// $insert inlineLexFunction
inline int Loxer::lex()
{
    return lex_();
}

inline void Loxer::preCode() 
{
    // optionally replace by your own code
}

inline void Loxer::postCode([[maybe_unused]] PostEnum_ type) 
{
    // optionally replace by your own code
}

inline void Loxer::print() 
{
    print_();
}


#endif // Loxer_H_INCLUDED_

