// Generated by Flexc++ V2.14.00 on Sun, 27 Aug 2023 09:11:20 +0100

#include <iostream>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <filesystem>

// $insert class_ih
#include "Loxer.ih"


    // s_ranges_: use (unsigned) characters as index to obtain
    //           that character's range-number.
    //           The range for EOF is defined in a constant in the
    //           class header file
size_t const LoxerBase::s_ranges_[] =
{
     0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 3, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
     5, 5, 5, 5, 5, 5, 5, 6, 7, 8, 9, 9, 9, 9, 9,10,11,12,13,14,15,16,17,18,18,
    18,18,18,18,18,18,18,18,19,20,21,22,23,24,24,25,25,25,25,25,25,25,25,25,25,
    25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,26,26,26,26,27,28,29,30,31,
    32,33,34,35,36,37,38,38,39,40,41,42,43,44,45,46,47,48,49,50,51,51,51,52,53,
    54,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,
    55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,
    55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,
    55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,
    55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,
    55,55,55,55,55,55,
};

// $insert startcondinfo
    // s_dfa_ contains the rows of *all* DFAs ordered by start state.  The
    // enum class StartCondition_is defined in the baseclass header.
    // StartCondition_::INITIAL is always 0.  Each entry defines the row to
    // transit to if the column's character range was sensed. Row numbers are
    // relative to the used DFA, and d_dfaBase_ is set to the first row of
    // the subset to use.  The row's final two values are respectively the
    // rule that may be matched at this state, and the rule's FINAL flag. If
    // the final value equals FINAL (= 1) then, if there's no continuation,
    // the rule is matched. If the BOL flag (8) is also set (so FINAL + BOL (=
    // 9) is set) then the rule only matches when d_atBOL is also true.
int const LoxerBase::s_dfa_[][59] =
{
    // INITIAL
    { 1, 2, 2, 1, 2, 1, 2, 3, 4, 1, 5, 6, 7, 8, 9,10,11,12,13, 1,
         14,15,16,17, 1,18, 1,18, 1,19,18,20,18,21,22,18,18,23,18,18,
         18,24,25,26,18,27,28,29,18,30,31,18,32, 1,33, 1,-1,    -1, -1},  // 0
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    40, -1},  // 1
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    39, -1},  // 2
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,34,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    30, -1},  // 3
    {35,35,35,35,35,35,35,35,36,35,35,35,35,35,35,35,35,35,35,35,
         35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,
         35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,-1,    40, -1},  // 4
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    19, -1},  // 5
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    20, -1},  // 6
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    29, -1},  // 7
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    26, -1},  // 8
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    23, -1},  // 9
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    25, -1},  // 10
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    24, -1},  // 11
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,37,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    28, -1},  // 12
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,38,-1,13,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    16, -1},  // 13
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    27, -1},  // 14
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,39,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    36, -1},  // 15
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,40,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    32, -1},  // 16
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,41,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    34, -1},  // 17
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 18
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,42,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 19
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,43,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 20
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,44,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 21
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,45,18,18,18,18,18,18,18,18,18,18,
         18,18,46,18,18,18,18,18,47,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 22
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,48,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 23
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,49,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 24
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,50,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 25
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,51,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 26
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,52,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 27
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,53,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 28
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,54,18,18,18,
         18,18,18,18,18,55,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 29
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,56,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 30
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,57,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 31
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    21, -1},  // 32
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    22, -1},  // 33
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    31, -1},  // 34
    {35,35,35,35,35,35,35,35,36,35,35,35,35,35,35,35,35,35,35,35,
         35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,
         35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,-1,    -1, -1},  // 35
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    18, -1},  // 36
    {37,37,-1,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,
         37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,
         37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,-1,    38, -1},  // 37
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,58,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    -1, -1},  // 38
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    37, -1},  // 39
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    33, -1},  // 40
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    35, -1},  // 41
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,59,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 42
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,60,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 43
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,61,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 44
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,62,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 45
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,63,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 46
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,64,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 47
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,     6, -1},  // 48
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,65,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 49
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,     8, -1},  // 50
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,66,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 51
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,67,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 52
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,68,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 53
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,69,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 54
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,70,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 55
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,71,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 56
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,72,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 57
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,58,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,    16, -1},  // 58
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,     0, -1},  // 59
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,73,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 60
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,74,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 61
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,75,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 62
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,     5, -1},  // 63
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,     4, -1},  // 64
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,     7, -1},  // 65
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,76,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 66
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,77,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 67
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,78,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 68
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,79,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 69
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,80,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 70
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    14, -1},  // 71
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,81,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 72
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,82,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 73
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,     2, -1},  // 74
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,83,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 75
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,84,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 76
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,85,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 77
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,86,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 78
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    12, -1},  // 79
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    13, -1},  // 80
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,87,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 81
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,     1, -1},  // 82
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,     3, -1},  // 83
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,     9, -1},  // 84
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,88,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    17, -1},  // 85
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    11, -1},  // 86
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    15, -1},  // 87
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1,
         -1,-1,-1,-1,-1,18,-1,18,-1,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,-1,-1,-1,-1,-1,    10, -1},  // 88
};


int const (*LoxerBase::s_dfaBase_[])[59] =
{
    s_dfa_ + 0,
};

size_t LoxerBase::s_istreamNr = 0;

// $insert inputImplementation
LoxerBase::Input::Input()
:
    d_in(0),
    d_lineNr(1)
{}

LoxerBase::Input::Input(std::istream *iStream, size_t lineNr)
:
    d_in(iStream),
    d_lineNr(lineNr)
{}

size_t LoxerBase::Input::get()
{
    switch (size_t ch = next())         // get the next input char
    {
        case '\n':
            ++d_lineNr;
        [[fallthrough]];

        default:
        return ch;
    }
}

size_t LoxerBase::Input::next()
{
    size_t ch;

    if (d_deque.empty())                // deque empty: next char fm d_in
    {
        if (d_in == 0)
            return AT_EOF;
        ch = d_in->get();
        return *d_in ? ch : static_cast<size_t>(AT_EOF);
    }

    ch = d_deque.front();
    d_deque.pop_front();

    return ch;
}

void LoxerBase::Input::reRead(size_t ch)
{
    if (ch < 0x100)
    {
        if (ch == '\n')
            --d_lineNr;
        d_deque.push_front(ch);
    }
}

void LoxerBase::Input::reRead(std::string const &str, size_t fm)
{
    for (size_t idx = str.size(); idx-- > fm; )
        reRead(str[idx]);
}

LoxerBase::LoxerBase(std::istream &in, std::ostream &out, bool keepCwd)
:
    d_out(new std::ostream(out.rdbuf())),
// $insert interactiveInit
    d_in(0),
    d_dfaBase_(s_dfa_)
{
    if (keepCwd)
        d_cwd = std::filesystem::current_path().string();
    p_pushStream(s_istream, new std::istream(in.rdbuf()));
}

void LoxerBase::switchStream_(std::istream &in, size_t lineNr)
{
    d_input->close();
    d_streamStack.back().input = { new std::istream(in.rdbuf()), lineNr };
}


LoxerBase::LoxerBase(std::string const &infilename, std::string const &outfilename, bool keepCwd)
:
    d_out(outfilename == "-"    ? new std::ostream(std::cout.rdbuf()) :
          outfilename == ""     ? new std::ostream(std::cerr.rdbuf()) :
                                  new std::ofstream(outfilename)),
    d_dfaBase_(s_dfa_)
{
    if (keepCwd)
        d_cwd = std::filesystem::current_path().string();

    p_pushStream(infilename, { new std::ifstream(infilename) });
    toCwd();
}

void LoxerBase::switchStreams(std::istream &in, std::ostream &out)
{
    switchStream_(in, 1);
    switchOstream(out);
}

void LoxerBase::switchIstream(std::string const &infilename)
{
    d_input->close();
    d_filename = infilename;

    d_streamStack.back() = 
        StreamStruct{ chgWorkingDir(d_filename), 
                      { new std::ifstream(infilename) } };

    d_atBOL = true;
}

void LoxerBase::switchStreams(std::string const &infilename,
                           std::string const &outfilename)
{
    switchOstream(outfilename);
    switchIstream(infilename);
}

void LoxerBase::pushStream(std::istream  &istr)
{
    p_pushStream("(istream)", new std::istream(istr.rdbuf())); //streamPtr);
}

void LoxerBase::pushStream(std::string const &name)
{
    std::istream *streamPtr = new std::ifstream(name);
    if (!*streamPtr)
    {
        delete streamPtr;
        throw std::runtime_error("Cannot read " + name);
    }
    p_pushStream(name, streamPtr);
}



void LoxerBase::toCwd() const
{
    using namespace std;
    using namespace filesystem;

    if (d_cwd.empty())
        return;

    error_code ec;
    current_path(d_cwd, ec);
};

// static
std::string LoxerBase::chgWorkingDir(std::string const &name)     // any name
{
    using namespace std;
    using namespace filesystem;

    if (name == s_istream)                              // used with istreams
        return name;
                                                        // a filename: get its
    auto path = absolute(name);                         // full pathname

    error_code ec;
    current_path(path.parent_path(), ec);

    return path.string();                               // return the pathname
}

void LoxerBase::p_pushStream(std::string const &name, std::istream *streamPtr)
{
    if (d_streamStack.size() == s_maxSizeofStreamStack_)
    {
        delete streamPtr;
        throw std::length_error("Max stream stack size exceeded");
    }

    d_filename = name;
    d_streamStack.push_back(
                    StreamStruct{chgWorkingDir(d_filename), { streamPtr } }
                  );

    d_input = &d_streamStack.back().input;

    d_atBOL = true;
}

void LoxerBase::switchOstream(std::ostream &out)
{
    *d_out << std::flush;
    d_out.reset(new std::ostream(out.rdbuf()));
}

// $insert debugFunctions
void LoxerBase::setDebug(bool onOff)
{}

bool LoxerBase::debug() const
{
    return false;
}

void LoxerBase::redo(size_t nChars)
{
    size_t from = nChars >= length() ? 0 : length() - nChars;
    d_input->reRead(d_matched, from);
    d_matched.resize(from);
}

void LoxerBase::switchOstream(std::string const &outfilename)
{
    *d_out << std::flush;
    d_out.reset(
            outfilename == "-"    ? new std::ostream(std::cout.rdbuf()) :
            outfilename == ""     ? new std::ostream(std::cerr.rdbuf()) :
                                    new std::ofstream(outfilename));
}


bool LoxerBase::popStream()
{
    using namespace std::filesystem;

    d_input->close();

    if (d_streamStack.size() <= 1)
        return false;

    d_streamStack.pop_back();

    d_filename = path{ chgWorkingDir(d_streamStack.back().pushedName) 
                     }.filename().string();

    d_input = &d_streamStack.back().input;

    return true;
}



  // See the manual's section `Run-time operations' section for an explanation
  // of this member.
LoxerBase::ActionType_ LoxerBase::actionType_(size_t range)
{
    d_nextState = d_dfaBase_[d_state][range];

    if (d_nextState != -1)                  // transition is possible
        return ActionType_::CONTINUE;

    if (knownFinalState())                  // FINAL state reached
        return ActionType_::MATCH;         

    if (d_matched.size())
        return ActionType_::ECHO_FIRST;    // no match, echo the 1st char

    return range != s_rangeOfEOF_ ? 
                ActionType_::ECHO_CH 
            : 
                ActionType_::RETURN;
}

void LoxerBase::accept(size_t nChars)          // old name: less
{
    if (nChars < d_matched.size())
    {
        d_input->reRead(d_matched, nChars);
        d_matched.resize(nChars);
    }
}

void LoxerBase::setMatchedSize(size_t length)
{
    d_input->reRead(d_matched, length);  // reread the tail section
    d_matched.resize(length);           // return what's left
}

  // At this point a rule has been matched.  The next character is not part of
  // the matched rule and is sent back to the input.  The final match length
  // is determined, the index of the matched rule is determined, and then
  // d_atBOL is updated. Finally the rule's index is returned.
  // The numbers behind the finalPtr assignments are explained in the 
  // manual's `Run-time operations' section.
size_t LoxerBase::matched_(size_t ch)
{
    d_input->reRead(ch);

    FinalData *finalPtr;
                            
    if (not d_atBOL)                    // not at BOL
        finalPtr = &d_final.std;        // then use the std rule (3, 4)

                                        // at BOL
    else if (not available(d_final.std.rule))   // only a BOL rule avail.
            finalPtr = &d_final.bol;            // use the BOL rule (6)

    else if (not available(d_final.bol.rule)) // only a std rule is avail.
        finalPtr = &d_final.std;        // use the std rule (7)
        
    else if (                           // Both are available (8)
        d_final.bol.length !=           // check lengths of matched texts
        d_final.std.length              // unequal lengths, use the rule
    )                                   // having the longer match length
        finalPtr =              
            d_final.bol.length > d_final.std.length ?
                &d_final.bol
            :
                &d_final.std;

    else                            // lengths are equal: use 1st rule
        finalPtr = 
            d_final.bol.rule < d_final.std.rule ?
                &d_final.bol
            :
                &d_final.std;

    setMatchedSize(finalPtr->length);

    d_atBOL = d_matched.back() == '\n';


    return finalPtr->rule;
}

size_t LoxerBase::getRange_(int ch)       // using int to prevent casts
{
    return ch == AT_EOF ? as<size_t>(s_rangeOfEOF_) : s_ranges_[ch];
}

  // At this point d_nextState contains the next state and continuation is
  // possible. The just read char. is appended to d_match
void LoxerBase::continue_(int ch)
{
    d_state = d_nextState;

    if (ch != AT_EOF)
        d_matched += ch;
}

void LoxerBase::echoCh_(size_t ch)
{
    *d_out << as<char>(ch);
    d_atBOL = ch == '\n';
}


   // At this point there is no continuation. The last character is
   // pushed back into the input stream as well as all but the first char. in
   // the buffer. The first char. in the buffer is echoed to stderr. 
   // If there isn't any 1st char yet then the current char doesn't fit any
   // rules and that char is then echoed
void LoxerBase::echoFirst_(size_t ch)
{
    d_input->reRead(ch);
    d_input->reRead(d_matched, 1);
    echoCh_(d_matched[0]);
}

    // Update the rules associated with the current state, do this separately
    // for BOL and std rules.
    // If a rule was set, update the rule index and the current d_matched
    // length. 
void LoxerBase::updateFinals_()
{
    size_t len = d_matched.size();

    int const *rf = d_dfaBase_[d_state] + s_finIdx_;

    if (rf[0] != -1)        // update to the latest std rule
    {
        d_final.std = FinalData { as<size_t>(rf[0]), len };
    }

    if (rf[1] != -1)        // update to the latest bol rule
    {
        d_final.bol = FinalData { as<size_t>(rf[1]), len };
    }
}

void LoxerBase::reset_()
{
    d_final = Final{ 
                    FinalData{s_unavailable, 0}, 
                    FinalData {s_unavailable, 0} 
                };

    d_state = 0;
    d_return = true;

    if (!d_more)
        d_matched.clear();

    d_more = false;
}

int Loxer::executeAction_(size_t ruleIdx)
try
{
    switch (ruleIdx)
    {
        // $insert actions
        case 0:
        {
#line 11 "loxer"
            return Tokens::AND;
        }
        break;
        case 1:
        {
#line 12 "loxer"
            return Tokens::CLASS;
        }
        break;
        case 2:
        {
#line 13 "loxer"
            return Tokens::ELSE;
        }
        break;
        case 3:
        {
#line 14 "loxer"
            return Tokens::FALSE;
        }
        break;
        case 4:
        {
#line 15 "loxer"
            return Tokens::FUN;
        }
        break;
        case 5:
        {
#line 16 "loxer"
            return Tokens::FOR;
        }
        break;
        case 6:
        {
#line 17 "loxer"
            return Tokens::IF;
        }
        break;
        case 7:
        {
#line 18 "loxer"
            return Tokens::NIL;
        }
        break;
        case 8:
        {
#line 19 "loxer"
            return Tokens::OR;
        }
        break;
        case 9:
        {
#line 20 "loxer"
            return Tokens::PRINT;
        }
        break;
        case 10:
        {
#line 21 "loxer"
            return Tokens::RETURN;
        }
        break;
        case 11:
        {
#line 22 "loxer"
            return Tokens::SUPER;
        }
        break;
        case 12:
        {
#line 23 "loxer"
            return Tokens::THIS;
        }
        break;
        case 13:
        {
#line 24 "loxer"
            return Tokens::TRUE;
        }
        break;
        case 14:
        {
#line 25 "loxer"
            return Tokens::VAR;
        }
        break;
        case 15:
        {
#line 26 "loxer"
            return Tokens::WHILE;
        }
        break;
        case 16:
        {
#line 27 "loxer"
            return Tokens::NUMBER;
        }
        break;
        case 17:
        {
#line 28 "loxer"
            return Tokens::IDENTIFIER;
        }
        break;
        case 18:
        {
#line 29 "loxer"
            return Tokens::STRING;
        }
        break;
        case 19:
        {
#line 30 "loxer"
            return Tokens::LEFT_PAREN;
        }
        break;
        case 20:
        {
#line 31 "loxer"
            return Tokens::RIGHT_PAREN;
        }
        break;
        case 21:
        {
#line 32 "loxer"
            return Tokens::LEFT_BRACE;
        }
        break;
        case 22:
        {
#line 33 "loxer"
            return Tokens::RIGHT_BRACE;
        }
        break;
        case 23:
        {
#line 34 "loxer"
            return Tokens::COMMA;
        }
        break;
        case 24:
        {
#line 35 "loxer"
            return Tokens::DOT;
        }
        break;
        case 25:
        {
#line 36 "loxer"
            return Tokens::MINUS;
        }
        break;
        case 26:
        {
#line 37 "loxer"
            return Tokens::PLUS;
        }
        break;
        case 27:
        {
#line 38 "loxer"
            return Tokens::SEMICOLON;
        }
        break;
        case 28:
        {
#line 39 "loxer"
            return Tokens::SLASH;
        }
        break;
        case 29:
        {
#line 40 "loxer"
            return Tokens::STAR;
        }
        break;
        case 30:
        {
#line 41 "loxer"
            return Tokens::BANG;
        }
        break;
        case 31:
        {
#line 42 "loxer"
            return Tokens::BANG_EQUAL;
        }
        break;
        case 32:
        {
#line 43 "loxer"
            return Tokens::EQUAL;
        }
        break;
        case 33:
        {
#line 44 "loxer"
            return Tokens::EQUAL_EQUAL;
        }
        break;
        case 34:
        {
#line 45 "loxer"
            return Tokens::GREATER;
        }
        break;
        case 35:
        {
#line 46 "loxer"
            return Tokens::GREATER_EQUAL;
        }
        break;
        case 36:
        {
#line 47 "loxer"
            return Tokens::LESS;
        }
        break;
        case 37:
        {
#line 48 "loxer"
            return Tokens::LESS_EQUAL;
        }
        break;
        case 38:
        {
#line 49 "loxer"
            accept(matched().length());
        }
        break;
        case 39:
        {
#line 50 "loxer"
            accept(1);
        }
        break;
        case 40:
        {
#line 51 "loxer"
            return matched()[0];
        }
        break;
    }
    noReturn_();
    return 0;
}
catch (Leave_ value)
{
    return static_cast<int>(value);
}

int Loxer::lex_()
{
    reset_();
    preCode();

    while (true)
    {
        size_t ch = get_();                // fetch next char
        size_t range = getRange_(ch);      // determine the range

        updateFinals_();                    // update the state's Final info

        switch (actionType_(range))        // determine the action
        {
            case ActionType_::CONTINUE:
                continue_(ch);
            continue;

            case ActionType_::MATCH:
            {
                d_token_ = executeAction_(matched_(ch));
                if (return_())
                {
                    print();
                    toCwd();
                    return d_token_;
                }
                break;
            }

            case ActionType_::ECHO_FIRST:
                echoFirst_(ch);
            break;

            case ActionType_::ECHO_CH:
                echoCh_(ch);
            break;

            case ActionType_::RETURN:
                if (!popStream())
                {
                     postCode(PostEnum_::END);
                     toCwd();
                     return 0;
                }
                postCode(PostEnum_::POP);
             continue;
        } // switch

        postCode(PostEnum_::WIP);

        reset_();
        preCode();
    } // while
}

void LoxerBase::print_() const
{
}


