// Generated by Bisonc++ V6.05.00 on Sun, 27 Aug 2023 09:11:20 +0100

// base/comment

// $insert class.ih
#include "Loxgram.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token is Reserved_::UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN_ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on errTok_
// which is applied. In this errTok_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
//      }

// base/declarations

namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum Reserved_
    {
        UNDETERMINED_   = -2,
        EOF_            = -1,
        errTok_         = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    inline bool operator&(StateType lhs, StateType rhs)
    {
        return (static_cast<int>(lhs) & rhs) != 0;
    }
    enum StateTransition
    {
        ACCEPT_   = 0,     // `ACCEPT' TRANSITION
    };

    struct PI_     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR_     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            StateType d_type;
            int       d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION_ = 10
    };

// Productions Info Records:
PI_ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {296, 0}, // 1: program ->  <empty>
     {296, 2}, // 2: program ->  program declaration
     {297, 1}, // 3: declaration ->  classDecl
     {297, 1}, // 4: declaration ->  funDecl
     {297, 1}, // 5: declaration ->  varDecl
     {297, 1}, // 6: declaration ->  statement
     {298, 5}, // 7: classDecl (CLASS) ->  CLASS identifier LEFT_BRACE optFunL RIGHT_BRACE
     {298, 7}, // 8: classDecl (CLASS) ->  CLASS identifier LESS identifier LEFT_BRACE optFunL RIGHT_BRACE
     {303, 0}, // 9: optFunL ->  <empty>
     {303, 1}, // 10: optFunL ->  funList
     {304, 2}, // 11: funList ->  funList function
     {304, 1}, // 12: funList ->  function
     {305, 5}, // 13: function (LEFT_PAREN) ->  identifier LEFT_PAREN optParamL RIGHT_PAREN block
     {299, 2}, // 14: funDecl (FUN) ->  FUN function
     {306, 0}, // 15: optParamL ->  <empty>
     {306, 1}, // 16: optParamL ->  paramList
     {308, 3}, // 17: paramList (COMMA) ->  paramList COMMA identifier
     {308, 1}, // 18: paramList ->  identifier
     {300, 5}, // 19: varDecl (VAR) ->  VAR identifier EQUAL expression SEMICOLON
     {300, 3}, // 20: varDecl (VAR) ->  VAR identifier SEMICOLON
     {301, 1}, // 21: statement ->  exprStmt
     {301, 1}, // 22: statement ->  forStmt
     {301, 1}, // 23: statement ->  ifStmt
     {301, 1}, // 24: statement ->  printStmt
     {301, 1}, // 25: statement ->  returnStmt
     {301, 1}, // 26: statement ->  whileStmt
     {301, 1}, // 27: statement ->  block
     {307, 3}, // 28: block (LEFT_BRACE) ->  LEFT_BRACE blockStmts RIGHT_BRACE
     {316, 2}, // 29: blockStmts ->  blockStmts declaration
     {316, 1}, // 30: blockStmts ->  declaration
     {310, 2}, // 31: exprStmt (SEMICOLON) ->  expression SEMICOLON
     {313, 3}, // 32: printStmt (PRINT) ->  PRINT expression SEMICOLON
     {314, 3}, // 33: returnStmt (RETURN) ->  RETURN optExpr SEMICOLON
     {312, 5}, // 34: ifStmt (IF) ->  IF LEFT_PAREN expression RIGHT_PAREN statement
     {312, 7}, // 35: ifStmt (IF) ->  IF LEFT_PAREN expression RIGHT_PAREN statement ELSE statement
     {315, 5}, // 36: whileStmt (WHILE) ->  WHILE LEFT_PAREN expression RIGHT_PAREN statement
     {311, 8}, // 37: forStmt (FOR) ->  FOR LEFT_PAREN forInit optExpr SEMICOLON optExpr RIGHT_PAREN statement
     {318, 1}, // 38: forInit (SEMICOLON) ->  SEMICOLON
     {318, 1}, // 39: forInit ->  varDecl
     {318, 1}, // 40: forInit ->  exprStmt
     {317, 0}, // 41: optExpr ->  <empty>
     {317, 1}, // 42: optExpr ->  expression
     {309, 1}, // 43: expression ->  assignment
     {309, 1}, // 44: expression ->  unary
     {309, 1}, // 45: expression ->  binary
     {309, 1}, // 46: expression ->  logical
     {309, 1}, // 47: expression ->  primary
     {309, 1}, // 48: expression ->  call
     {319, 3}, // 49: assignment (EQUAL) ->  identifier EQUAL expression
     {319, 5}, // 50: assignment (DOT) ->  primary DOT identifier EQUAL expression
     {319, 5}, // 51: assignment (DOT) ->  call DOT identifier EQUAL expression
     {320, 2}, // 52: unary (BANG) ->  BANG expression
     {320, 2}, // 53: unary (UMINUS) ->  MINUS expression
     {321, 3}, // 54: binary (EQUAL_EQUAL) ->  expression EQUAL_EQUAL expression
     {321, 3}, // 55: binary (BANG_EQUAL) ->  expression BANG_EQUAL expression
     {321, 3}, // 56: binary (LESS) ->  expression LESS expression
     {321, 3}, // 57: binary (LESS_EQUAL) ->  expression LESS_EQUAL expression
     {321, 3}, // 58: binary (GREATER) ->  expression GREATER expression
     {321, 3}, // 59: binary (GREATER_EQUAL) ->  expression GREATER_EQUAL expression
     {321, 3}, // 60: binary (PLUS) ->  expression PLUS expression
     {321, 3}, // 61: binary (MINUS) ->  expression MINUS expression
     {321, 3}, // 62: binary (STAR) ->  expression STAR expression
     {321, 3}, // 63: binary (SLASH) ->  expression SLASH expression
     {322, 3}, // 64: logical (OR) ->  expression OR expression
     {322, 3}, // 65: logical (AND) ->  expression AND expression
     {323, 1}, // 66: primary ->  identifier
     {323, 1}, // 67: primary (NUMBER) ->  NUMBER
     {323, 1}, // 68: primary (STRING) ->  STRING
     {323, 1}, // 69: primary (TRUE) ->  TRUE
     {323, 1}, // 70: primary (FALSE) ->  FALSE
     {323, 1}, // 71: primary (NIL) ->  NIL
     {323, 3}, // 72: primary (LEFT_PAREN) ->  LEFT_PAREN expression RIGHT_PAREN
     {323, 1}, // 73: primary (THIS) ->  THIS
     {323, 3}, // 74: primary (SUPER) ->  SUPER DOT identifier
     {302, 1}, // 75: identifier (IDENTIFIER) ->  IDENTIFIER
     {324, 2}, // 76: call ->  primary getList
     {326, 0}, // 77: optExprL ->  <empty>
     {326, 1}, // 78: optExprL ->  exprList
     {327, 3}, // 79: exprList (COMMA) ->  exprList COMMA expression
     {327, 1}, // 80: exprList ->  expression
     {325, 3}, // 81: getList (DOT) ->  getList DOT identifier
     {325, 4}, // 82: getList (LEFT_PAREN) ->  getList LEFT_PAREN optExprL RIGHT_PAREN
     {325, 2}, // 83: getList (DOT) ->  DOT identifier
     {325, 3}, // 84: getList (LEFT_PAREN) ->  LEFT_PAREN optExprL RIGHT_PAREN
     {328, 1}, // 85: program_$ ->  program
};

// State info and SR_ transitions for each state.


SR_ s_0[] =
{
    { { DEF_RED}, {  2} },           
    { {     296}, {  1} }, // program
    { {       0}, { -1} },           
};

SR_ s_1[] =
{
    { { REQ_TOKEN}, {      42} },               
    { {       297}, {       2} }, // declaration
    { {       298}, {       3} }, // classDecl  
    { {       299}, {       4} }, // funDecl    
    { {       300}, {       5} }, // varDecl    
    { {       301}, {       6} }, // statement  
    { {       267}, {       7} }, // CLASS      
    { {       270}, {       8} }, // FUN        
    { {       279}, {       9} }, // VAR        
    { {       310}, {      10} }, // exprStmt   
    { {       311}, {      11} }, // forStmt    
    { {       312}, {      12} }, // ifStmt     
    { {       313}, {      13} }, // printStmt  
    { {       314}, {      14} }, // returnStmt 
    { {       315}, {      15} }, // whileStmt  
    { {       307}, {      16} }, // block      
    { {       309}, {      17} }, // expression 
    { {       271}, {      18} }, // FOR        
    { {       272}, {      19} }, // IF         
    { {       274}, {      20} }, // PRINT      
    { {       275}, {      21} }, // RETURN     
    { {       280}, {      22} }, // WHILE      
    { {       259}, {      23} }, // LEFT_BRACE 
    { {       319}, {      24} }, // assignment 
    { {       320}, {      25} }, // unary      
    { {       321}, {      26} }, // binary     
    { {       322}, {      27} }, // logical    
    { {       323}, {      28} }, // primary    
    { {       324}, {      29} }, // call       
    { {       302}, {      30} }, // identifier 
    { {       294}, {      31} }, // BANG       
    { {       290}, {      32} }, // MINUS      
    { {       266}, {      33} }, // NUMBER     
    { {       265}, {      34} }, // STRING     
    { {       278}, {      35} }, // TRUE       
    { {       269}, {      36} }, // FALSE      
    { {       273}, {      37} }, // NIL        
    { {       257}, {      38} }, // LEFT_PAREN 
    { {       277}, {      39} }, // THIS       
    { {       276}, {      40} }, // SUPER      
    { {       264}, {      41} }, // IDENTIFIER 
    { {      EOF_}, { ACCEPT_} },               
    { {         0}, {       0} },               
};

SR_ s_2[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR_ s_3[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR_ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR_ s_5[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR_ s_6[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR_ s_7[] =
{
    { { REQ_TOKEN}, {  3} },              
    { {       302}, { 42} }, // identifier
    { {       264}, { 41} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR_ s_8[] =
{
    { { REQ_TOKEN}, {  4} },              
    { {       305}, { 43} }, // function  
    { {       302}, { 44} }, // identifier
    { {       264}, { 41} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR_ s_9[] =
{
    { { REQ_TOKEN}, {  3} },              
    { {       302}, { 45} }, // identifier
    { {       264}, { 41} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR_ s_10[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR_ s_11[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR_ s_12[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR_ s_13[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR_ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR_ s_15[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR_ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR_ s_17[] =
{
    { { REQ_TOKEN}, { 14} },                 
    { {       263}, { 46} }, // SEMICOLON    
    { {       285}, { 47} }, // EQUAL_EQUAL  
    { {       284}, { 48} }, // BANG_EQUAL   
    { {       288}, { 49} }, // LESS         
    { {       289}, { 50} }, // LESS_EQUAL   
    { {       286}, { 51} }, // GREATER      
    { {       287}, { 52} }, // GREATER_EQUAL
    { {       291}, { 53} }, // PLUS         
    { {       290}, { 54} }, // MINUS        
    { {       293}, { 55} }, // STAR         
    { {       292}, { 56} }, // SLASH        
    { {       282}, { 57} }, // OR           
    { {       283}, { 58} }, // AND          
    { {         0}, {  0} },                 
};

SR_ s_18[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       257}, { 59} }, // LEFT_PAREN
    { {         0}, {  0} },              
};

SR_ s_19[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       257}, { 60} }, // LEFT_PAREN
    { {         0}, {  0} },              
};

SR_ s_20[] =
{
    { { REQ_TOKEN}, { 20} },              
    { {       309}, { 61} }, // expression
    { {       319}, { 24} }, // assignment
    { {       320}, { 25} }, // unary     
    { {       321}, { 26} }, // binary    
    { {       322}, { 27} }, // logical   
    { {       323}, { 28} }, // primary   
    { {       324}, { 29} }, // call      
    { {       302}, { 30} }, // identifier
    { {       294}, { 31} }, // BANG      
    { {       290}, { 32} }, // MINUS     
    { {       266}, { 33} }, // NUMBER    
    { {       265}, { 34} }, // STRING    
    { {       278}, { 35} }, // TRUE      
    { {       269}, { 36} }, // FALSE     
    { {       273}, { 37} }, // NIL       
    { {       257}, { 38} }, // LEFT_PAREN
    { {       277}, { 39} }, // THIS      
    { {       276}, { 40} }, // SUPER     
    { {       264}, { 41} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR_ s_21[] =
{
    { { REQ_DEF}, {  21} },              
    { {     317}, {  62} }, // optExpr   
    { {     309}, {  63} }, // expression
    { {     319}, {  24} }, // assignment
    { {     320}, {  25} }, // unary     
    { {     321}, {  26} }, // binary    
    { {     322}, {  27} }, // logical   
    { {     323}, {  28} }, // primary   
    { {     324}, {  29} }, // call      
    { {     302}, {  30} }, // identifier
    { {     294}, {  31} }, // BANG      
    { {     290}, {  32} }, // MINUS     
    { {     266}, {  33} }, // NUMBER    
    { {     265}, {  34} }, // STRING    
    { {     278}, {  35} }, // TRUE      
    { {     269}, {  36} }, // FALSE     
    { {     273}, {  37} }, // NIL       
    { {     257}, {  38} }, // LEFT_PAREN
    { {     277}, {  39} }, // THIS      
    { {     276}, {  40} }, // SUPER     
    { {     264}, {  41} }, // IDENTIFIER
    { {       0}, { -41} },              
};

SR_ s_22[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       257}, { 64} }, // LEFT_PAREN
    { {         0}, {  0} },              
};

SR_ s_23[] =
{
    { { REQ_TOKEN}, { 42} },               
    { {       316}, { 65} }, // blockStmts 
    { {       297}, { 66} }, // declaration
    { {       298}, {  3} }, // classDecl  
    { {       299}, {  4} }, // funDecl    
    { {       300}, {  5} }, // varDecl    
    { {       301}, {  6} }, // statement  
    { {       267}, {  7} }, // CLASS      
    { {       270}, {  8} }, // FUN        
    { {       279}, {  9} }, // VAR        
    { {       310}, { 10} }, // exprStmt   
    { {       311}, { 11} }, // forStmt    
    { {       312}, { 12} }, // ifStmt     
    { {       313}, { 13} }, // printStmt  
    { {       314}, { 14} }, // returnStmt 
    { {       315}, { 15} }, // whileStmt  
    { {       307}, { 16} }, // block      
    { {       309}, { 17} }, // expression 
    { {       271}, { 18} }, // FOR        
    { {       272}, { 19} }, // IF         
    { {       274}, { 20} }, // PRINT      
    { {       275}, { 21} }, // RETURN     
    { {       280}, { 22} }, // WHILE      
    { {       259}, { 23} }, // LEFT_BRACE 
    { {       319}, { 24} }, // assignment 
    { {       320}, { 25} }, // unary      
    { {       321}, { 26} }, // binary     
    { {       322}, { 27} }, // logical    
    { {       323}, { 28} }, // primary    
    { {       324}, { 29} }, // call       
    { {       302}, { 30} }, // identifier 
    { {       294}, { 31} }, // BANG       
    { {       290}, { 32} }, // MINUS      
    { {       266}, { 33} }, // NUMBER     
    { {       265}, { 34} }, // STRING     
    { {       278}, { 35} }, // TRUE       
    { {       269}, { 36} }, // FALSE      
    { {       273}, { 37} }, // NIL        
    { {       257}, { 38} }, // LEFT_PAREN 
    { {       277}, { 39} }, // THIS       
    { {       276}, { 40} }, // SUPER      
    { {       264}, { 41} }, // IDENTIFIER 
    { {         0}, {  0} },               
};

SR_ s_24[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR_ s_25[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR_ s_26[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR_ s_27[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR_ s_28[] =
{
    { { REQ_DEF}, {   4} },              
    { {     262}, {  67} }, // DOT       
    { {     325}, {  68} }, // getList   
    { {     257}, {  69} }, // LEFT_PAREN
    { {       0}, { -47} },              
};

SR_ s_29[] =
{
    { { REQ_DEF}, {   2} },       
    { {     262}, {  70} }, // DOT
    { {       0}, { -48} },       
};

SR_ s_30[] =
{
    { { REQ_DEF}, {   2} },         
    { {     281}, {  71} }, // EQUAL
    { {       0}, { -66} },         
};

SR_ s_31[] =
{
    { { REQ_TOKEN}, { 20} },              
    { {       309}, { 72} }, // expression
    { {       319}, { 24} }, // assignment
    { {       320}, { 25} }, // unary     
    { {       321}, { 26} }, // binary    
    { {       322}, { 27} }, // logical   
    { {       323}, { 28} }, // primary   
    { {       324}, { 29} }, // call      
    { {       302}, { 30} }, // identifier
    { {       294}, { 31} }, // BANG      
    { {       290}, { 32} }, // MINUS     
    { {       266}, { 33} }, // NUMBER    
    { {       265}, { 34} }, // STRING    
    { {       278}, { 35} }, // TRUE      
    { {       269}, { 36} }, // FALSE     
    { {       273}, { 37} }, // NIL       
    { {       257}, { 38} }, // LEFT_PAREN
    { {       277}, { 39} }, // THIS      
    { {       276}, { 40} }, // SUPER     
    { {       264}, { 41} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR_ s_32[] =
{
    { { REQ_TOKEN}, { 20} },              
    { {       309}, { 73} }, // expression
    { {       319}, { 24} }, // assignment
    { {       320}, { 25} }, // unary     
    { {       321}, { 26} }, // binary    
    { {       322}, { 27} }, // logical   
    { {       323}, { 28} }, // primary   
    { {       324}, { 29} }, // call      
    { {       302}, { 30} }, // identifier
    { {       294}, { 31} }, // BANG      
    { {       290}, { 32} }, // MINUS     
    { {       266}, { 33} }, // NUMBER    
    { {       265}, { 34} }, // STRING    
    { {       278}, { 35} }, // TRUE      
    { {       269}, { 36} }, // FALSE     
    { {       273}, { 37} }, // NIL       
    { {       257}, { 38} }, // LEFT_PAREN
    { {       277}, { 39} }, // THIS      
    { {       276}, { 40} }, // SUPER     
    { {       264}, { 41} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR_ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -67} }, 
};

SR_ s_34[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -68} }, 
};

SR_ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -69} }, 
};

SR_ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -70} }, 
};

SR_ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -71} }, 
};

SR_ s_38[] =
{
    { { REQ_TOKEN}, { 20} },              
    { {       309}, { 74} }, // expression
    { {       319}, { 24} }, // assignment
    { {       320}, { 25} }, // unary     
    { {       321}, { 26} }, // binary    
    { {       322}, { 27} }, // logical   
    { {       323}, { 28} }, // primary   
    { {       324}, { 29} }, // call      
    { {       302}, { 30} }, // identifier
    { {       294}, { 31} }, // BANG      
    { {       290}, { 32} }, // MINUS     
    { {       266}, { 33} }, // NUMBER    
    { {       265}, { 34} }, // STRING    
    { {       278}, { 35} }, // TRUE      
    { {       269}, { 36} }, // FALSE     
    { {       273}, { 37} }, // NIL       
    { {       257}, { 38} }, // LEFT_PAREN
    { {       277}, { 39} }, // THIS      
    { {       276}, { 40} }, // SUPER     
    { {       264}, { 41} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR_ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -73} }, 
};

SR_ s_40[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       262}, { 75} }, // DOT
    { {         0}, {  0} },       
};

SR_ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -75} }, 
};

SR_ s_42[] =
{
    { { REQ_TOKEN}, {  3} },              
    { {       259}, { 76} }, // LEFT_BRACE
    { {       288}, { 77} }, // LESS      
    { {         0}, {  0} },              
};

SR_ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR_ s_44[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       257}, { 78} }, // LEFT_PAREN
    { {         0}, {  0} },              
};

SR_ s_45[] =
{
    { { REQ_TOKEN}, {  3} },             
    { {       281}, { 79} }, // EQUAL    
    { {       263}, { 80} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR_ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR_ s_47[] =
{
    { { REQ_TOKEN}, { 20} },              
    { {       309}, { 81} }, // expression
    { {       319}, { 24} }, // assignment
    { {       320}, { 25} }, // unary     
    { {       321}, { 26} }, // binary    
    { {       322}, { 27} }, // logical   
    { {       323}, { 28} }, // primary   
    { {       324}, { 29} }, // call      
    { {       302}, { 30} }, // identifier
    { {       294}, { 31} }, // BANG      
    { {       290}, { 32} }, // MINUS     
    { {       266}, { 33} }, // NUMBER    
    { {       265}, { 34} }, // STRING    
    { {       278}, { 35} }, // TRUE      
    { {       269}, { 36} }, // FALSE     
    { {       273}, { 37} }, // NIL       
    { {       257}, { 38} }, // LEFT_PAREN
    { {       277}, { 39} }, // THIS      
    { {       276}, { 40} }, // SUPER     
    { {       264}, { 41} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR_ s_48[] =
{
    { { REQ_TOKEN}, { 20} },              
    { {       309}, { 82} }, // expression
    { {       319}, { 24} }, // assignment
    { {       320}, { 25} }, // unary     
    { {       321}, { 26} }, // binary    
    { {       322}, { 27} }, // logical   
    { {       323}, { 28} }, // primary   
    { {       324}, { 29} }, // call      
    { {       302}, { 30} }, // identifier
    { {       294}, { 31} }, // BANG      
    { {       290}, { 32} }, // MINUS     
    { {       266}, { 33} }, // NUMBER    
    { {       265}, { 34} }, // STRING    
    { {       278}, { 35} }, // TRUE      
    { {       269}, { 36} }, // FALSE     
    { {       273}, { 37} }, // NIL       
    { {       257}, { 38} }, // LEFT_PAREN
    { {       277}, { 39} }, // THIS      
    { {       276}, { 40} }, // SUPER     
    { {       264}, { 41} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR_ s_49[] =
{
    { { REQ_TOKEN}, { 20} },              
    { {       309}, { 83} }, // expression
    { {       319}, { 24} }, // assignment
    { {       320}, { 25} }, // unary     
    { {       321}, { 26} }, // binary    
    { {       322}, { 27} }, // logical   
    { {       323}, { 28} }, // primary   
    { {       324}, { 29} }, // call      
    { {       302}, { 30} }, // identifier
    { {       294}, { 31} }, // BANG      
    { {       290}, { 32} }, // MINUS     
    { {       266}, { 33} }, // NUMBER    
    { {       265}, { 34} }, // STRING    
    { {       278}, { 35} }, // TRUE      
    { {       269}, { 36} }, // FALSE     
    { {       273}, { 37} }, // NIL       
    { {       257}, { 38} }, // LEFT_PAREN
    { {       277}, { 39} }, // THIS      
    { {       276}, { 40} }, // SUPER     
    { {       264}, { 41} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR_ s_50[] =
{
    { { REQ_TOKEN}, { 20} },              
    { {       309}, { 84} }, // expression
    { {       319}, { 24} }, // assignment
    { {       320}, { 25} }, // unary     
    { {       321}, { 26} }, // binary    
    { {       322}, { 27} }, // logical   
    { {       323}, { 28} }, // primary   
    { {       324}, { 29} }, // call      
    { {       302}, { 30} }, // identifier
    { {       294}, { 31} }, // BANG      
    { {       290}, { 32} }, // MINUS     
    { {       266}, { 33} }, // NUMBER    
    { {       265}, { 34} }, // STRING    
    { {       278}, { 35} }, // TRUE      
    { {       269}, { 36} }, // FALSE     
    { {       273}, { 37} }, // NIL       
    { {       257}, { 38} }, // LEFT_PAREN
    { {       277}, { 39} }, // THIS      
    { {       276}, { 40} }, // SUPER     
    { {       264}, { 41} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR_ s_51[] =
{
    { { REQ_TOKEN}, { 20} },              
    { {       309}, { 85} }, // expression
    { {       319}, { 24} }, // assignment
    { {       320}, { 25} }, // unary     
    { {       321}, { 26} }, // binary    
    { {       322}, { 27} }, // logical   
    { {       323}, { 28} }, // primary   
    { {       324}, { 29} }, // call      
    { {       302}, { 30} }, // identifier
    { {       294}, { 31} }, // BANG      
    { {       290}, { 32} }, // MINUS     
    { {       266}, { 33} }, // NUMBER    
    { {       265}, { 34} }, // STRING    
    { {       278}, { 35} }, // TRUE      
    { {       269}, { 36} }, // FALSE     
    { {       273}, { 37} }, // NIL       
    { {       257}, { 38} }, // LEFT_PAREN
    { {       277}, { 39} }, // THIS      
    { {       276}, { 40} }, // SUPER     
    { {       264}, { 41} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR_ s_52[] =
{
    { { REQ_TOKEN}, { 20} },              
    { {       309}, { 86} }, // expression
    { {       319}, { 24} }, // assignment
    { {       320}, { 25} }, // unary     
    { {       321}, { 26} }, // binary    
    { {       322}, { 27} }, // logical   
    { {       323}, { 28} }, // primary   
    { {       324}, { 29} }, // call      
    { {       302}, { 30} }, // identifier
    { {       294}, { 31} }, // BANG      
    { {       290}, { 32} }, // MINUS     
    { {       266}, { 33} }, // NUMBER    
    { {       265}, { 34} }, // STRING    
    { {       278}, { 35} }, // TRUE      
    { {       269}, { 36} }, // FALSE     
    { {       273}, { 37} }, // NIL       
    { {       257}, { 38} }, // LEFT_PAREN
    { {       277}, { 39} }, // THIS      
    { {       276}, { 40} }, // SUPER     
    { {       264}, { 41} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR_ s_53[] =
{
    { { REQ_TOKEN}, { 20} },              
    { {       309}, { 87} }, // expression
    { {       319}, { 24} }, // assignment
    { {       320}, { 25} }, // unary     
    { {       321}, { 26} }, // binary    
    { {       322}, { 27} }, // logical   
    { {       323}, { 28} }, // primary   
    { {       324}, { 29} }, // call      
    { {       302}, { 30} }, // identifier
    { {       294}, { 31} }, // BANG      
    { {       290}, { 32} }, // MINUS     
    { {       266}, { 33} }, // NUMBER    
    { {       265}, { 34} }, // STRING    
    { {       278}, { 35} }, // TRUE      
    { {       269}, { 36} }, // FALSE     
    { {       273}, { 37} }, // NIL       
    { {       257}, { 38} }, // LEFT_PAREN
    { {       277}, { 39} }, // THIS      
    { {       276}, { 40} }, // SUPER     
    { {       264}, { 41} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR_ s_54[] =
{
    { { REQ_TOKEN}, { 20} },              
    { {       309}, { 88} }, // expression
    { {       319}, { 24} }, // assignment
    { {       320}, { 25} }, // unary     
    { {       321}, { 26} }, // binary    
    { {       322}, { 27} }, // logical   
    { {       323}, { 28} }, // primary   
    { {       324}, { 29} }, // call      
    { {       302}, { 30} }, // identifier
    { {       294}, { 31} }, // BANG      
    { {       290}, { 32} }, // MINUS     
    { {       266}, { 33} }, // NUMBER    
    { {       265}, { 34} }, // STRING    
    { {       278}, { 35} }, // TRUE      
    { {       269}, { 36} }, // FALSE     
    { {       273}, { 37} }, // NIL       
    { {       257}, { 38} }, // LEFT_PAREN
    { {       277}, { 39} }, // THIS      
    { {       276}, { 40} }, // SUPER     
    { {       264}, { 41} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR_ s_55[] =
{
    { { REQ_TOKEN}, { 20} },              
    { {       309}, { 89} }, // expression
    { {       319}, { 24} }, // assignment
    { {       320}, { 25} }, // unary     
    { {       321}, { 26} }, // binary    
    { {       322}, { 27} }, // logical   
    { {       323}, { 28} }, // primary   
    { {       324}, { 29} }, // call      
    { {       302}, { 30} }, // identifier
    { {       294}, { 31} }, // BANG      
    { {       290}, { 32} }, // MINUS     
    { {       266}, { 33} }, // NUMBER    
    { {       265}, { 34} }, // STRING    
    { {       278}, { 35} }, // TRUE      
    { {       269}, { 36} }, // FALSE     
    { {       273}, { 37} }, // NIL       
    { {       257}, { 38} }, // LEFT_PAREN
    { {       277}, { 39} }, // THIS      
    { {       276}, { 40} }, // SUPER     
    { {       264}, { 41} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR_ s_56[] =
{
    { { REQ_TOKEN}, { 20} },              
    { {       309}, { 90} }, // expression
    { {       319}, { 24} }, // assignment
    { {       320}, { 25} }, // unary     
    { {       321}, { 26} }, // binary    
    { {       322}, { 27} }, // logical   
    { {       323}, { 28} }, // primary   
    { {       324}, { 29} }, // call      
    { {       302}, { 30} }, // identifier
    { {       294}, { 31} }, // BANG      
    { {       290}, { 32} }, // MINUS     
    { {       266}, { 33} }, // NUMBER    
    { {       265}, { 34} }, // STRING    
    { {       278}, { 35} }, // TRUE      
    { {       269}, { 36} }, // FALSE     
    { {       273}, { 37} }, // NIL       
    { {       257}, { 38} }, // LEFT_PAREN
    { {       277}, { 39} }, // THIS      
    { {       276}, { 40} }, // SUPER     
    { {       264}, { 41} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR_ s_57[] =
{
    { { REQ_TOKEN}, { 20} },              
    { {       309}, { 91} }, // expression
    { {       319}, { 24} }, // assignment
    { {       320}, { 25} }, // unary     
    { {       321}, { 26} }, // binary    
    { {       322}, { 27} }, // logical   
    { {       323}, { 28} }, // primary   
    { {       324}, { 29} }, // call      
    { {       302}, { 30} }, // identifier
    { {       294}, { 31} }, // BANG      
    { {       290}, { 32} }, // MINUS     
    { {       266}, { 33} }, // NUMBER    
    { {       265}, { 34} }, // STRING    
    { {       278}, { 35} }, // TRUE      
    { {       269}, { 36} }, // FALSE     
    { {       273}, { 37} }, // NIL       
    { {       257}, { 38} }, // LEFT_PAREN
    { {       277}, { 39} }, // THIS      
    { {       276}, { 40} }, // SUPER     
    { {       264}, { 41} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR_ s_58[] =
{
    { { REQ_TOKEN}, { 20} },              
    { {       309}, { 92} }, // expression
    { {       319}, { 24} }, // assignment
    { {       320}, { 25} }, // unary     
    { {       321}, { 26} }, // binary    
    { {       322}, { 27} }, // logical   
    { {       323}, { 28} }, // primary   
    { {       324}, { 29} }, // call      
    { {       302}, { 30} }, // identifier
    { {       294}, { 31} }, // BANG      
    { {       290}, { 32} }, // MINUS     
    { {       266}, { 33} }, // NUMBER    
    { {       265}, { 34} }, // STRING    
    { {       278}, { 35} }, // TRUE      
    { {       269}, { 36} }, // FALSE     
    { {       273}, { 37} }, // NIL       
    { {       257}, { 38} }, // LEFT_PAREN
    { {       277}, { 39} }, // THIS      
    { {       276}, { 40} }, // SUPER     
    { {       264}, { 41} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR_ s_59[] =
{
    { { REQ_TOKEN}, { 25} },              
    { {       318}, { 93} }, // forInit   
    { {       263}, { 94} }, // SEMICOLON 
    { {       300}, { 95} }, // varDecl   
    { {       310}, { 96} }, // exprStmt  
    { {       279}, {  9} }, // VAR       
    { {       309}, { 17} }, // expression
    { {       319}, { 24} }, // assignment
    { {       320}, { 25} }, // unary     
    { {       321}, { 26} }, // binary    
    { {       322}, { 27} }, // logical   
    { {       323}, { 28} }, // primary   
    { {       324}, { 29} }, // call      
    { {       302}, { 30} }, // identifier
    { {       294}, { 31} }, // BANG      
    { {       290}, { 32} }, // MINUS     
    { {       266}, { 33} }, // NUMBER    
    { {       265}, { 34} }, // STRING    
    { {       278}, { 35} }, // TRUE      
    { {       269}, { 36} }, // FALSE     
    { {       273}, { 37} }, // NIL       
    { {       257}, { 38} }, // LEFT_PAREN
    { {       277}, { 39} }, // THIS      
    { {       276}, { 40} }, // SUPER     
    { {       264}, { 41} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR_ s_60[] =
{
    { { REQ_TOKEN}, { 20} },              
    { {       309}, { 97} }, // expression
    { {       319}, { 24} }, // assignment
    { {       320}, { 25} }, // unary     
    { {       321}, { 26} }, // binary    
    { {       322}, { 27} }, // logical   
    { {       323}, { 28} }, // primary   
    { {       324}, { 29} }, // call      
    { {       302}, { 30} }, // identifier
    { {       294}, { 31} }, // BANG      
    { {       290}, { 32} }, // MINUS     
    { {       266}, { 33} }, // NUMBER    
    { {       265}, { 34} }, // STRING    
    { {       278}, { 35} }, // TRUE      
    { {       269}, { 36} }, // FALSE     
    { {       273}, { 37} }, // NIL       
    { {       257}, { 38} }, // LEFT_PAREN
    { {       277}, { 39} }, // THIS      
    { {       276}, { 40} }, // SUPER     
    { {       264}, { 41} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR_ s_61[] =
{
    { { REQ_TOKEN}, { 14} },                 
    { {       263}, { 98} }, // SEMICOLON    
    { {       285}, { 47} }, // EQUAL_EQUAL  
    { {       284}, { 48} }, // BANG_EQUAL   
    { {       288}, { 49} }, // LESS         
    { {       289}, { 50} }, // LESS_EQUAL   
    { {       286}, { 51} }, // GREATER      
    { {       287}, { 52} }, // GREATER_EQUAL
    { {       291}, { 53} }, // PLUS         
    { {       290}, { 54} }, // MINUS        
    { {       293}, { 55} }, // STAR         
    { {       292}, { 56} }, // SLASH        
    { {       282}, { 57} }, // OR           
    { {       283}, { 58} }, // AND          
    { {         0}, {  0} },                 
};

SR_ s_62[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       263}, { 99} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR_ s_63[] =
{
    { { REQ_DEF}, {  13} },                 
    { {     285}, {  47} }, // EQUAL_EQUAL  
    { {     284}, {  48} }, // BANG_EQUAL   
    { {     288}, {  49} }, // LESS         
    { {     289}, {  50} }, // LESS_EQUAL   
    { {     286}, {  51} }, // GREATER      
    { {     287}, {  52} }, // GREATER_EQUAL
    { {     291}, {  53} }, // PLUS         
    { {     290}, {  54} }, // MINUS        
    { {     293}, {  55} }, // STAR         
    { {     292}, {  56} }, // SLASH        
    { {     282}, {  57} }, // OR           
    { {     283}, {  58} }, // AND          
    { {       0}, { -42} },                 
};

SR_ s_64[] =
{
    { { REQ_TOKEN}, {  20} },              
    { {       309}, { 100} }, // expression
    { {       319}, {  24} }, // assignment
    { {       320}, {  25} }, // unary     
    { {       321}, {  26} }, // binary    
    { {       322}, {  27} }, // logical   
    { {       323}, {  28} }, // primary   
    { {       324}, {  29} }, // call      
    { {       302}, {  30} }, // identifier
    { {       294}, {  31} }, // BANG      
    { {       290}, {  32} }, // MINUS     
    { {       266}, {  33} }, // NUMBER    
    { {       265}, {  34} }, // STRING    
    { {       278}, {  35} }, // TRUE      
    { {       269}, {  36} }, // FALSE     
    { {       273}, {  37} }, // NIL       
    { {       257}, {  38} }, // LEFT_PAREN
    { {       277}, {  39} }, // THIS      
    { {       276}, {  40} }, // SUPER     
    { {       264}, {  41} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR_ s_65[] =
{
    { { REQ_TOKEN}, {  42} },               
    { {       260}, { 101} }, // RIGHT_BRACE
    { {       297}, { 102} }, // declaration
    { {       298}, {   3} }, // classDecl  
    { {       299}, {   4} }, // funDecl    
    { {       300}, {   5} }, // varDecl    
    { {       301}, {   6} }, // statement  
    { {       267}, {   7} }, // CLASS      
    { {       270}, {   8} }, // FUN        
    { {       279}, {   9} }, // VAR        
    { {       310}, {  10} }, // exprStmt   
    { {       311}, {  11} }, // forStmt    
    { {       312}, {  12} }, // ifStmt     
    { {       313}, {  13} }, // printStmt  
    { {       314}, {  14} }, // returnStmt 
    { {       315}, {  15} }, // whileStmt  
    { {       307}, {  16} }, // block      
    { {       309}, {  17} }, // expression 
    { {       271}, {  18} }, // FOR        
    { {       272}, {  19} }, // IF         
    { {       274}, {  20} }, // PRINT      
    { {       275}, {  21} }, // RETURN     
    { {       280}, {  22} }, // WHILE      
    { {       259}, {  23} }, // LEFT_BRACE 
    { {       319}, {  24} }, // assignment 
    { {       320}, {  25} }, // unary      
    { {       321}, {  26} }, // binary     
    { {       322}, {  27} }, // logical    
    { {       323}, {  28} }, // primary    
    { {       324}, {  29} }, // call       
    { {       302}, {  30} }, // identifier 
    { {       294}, {  31} }, // BANG       
    { {       290}, {  32} }, // MINUS      
    { {       266}, {  33} }, // NUMBER     
    { {       265}, {  34} }, // STRING     
    { {       278}, {  35} }, // TRUE       
    { {       269}, {  36} }, // FALSE      
    { {       273}, {  37} }, // NIL        
    { {       257}, {  38} }, // LEFT_PAREN 
    { {       277}, {  39} }, // THIS       
    { {       276}, {  40} }, // SUPER      
    { {       264}, {  41} }, // IDENTIFIER 
    { {         0}, {   0} },               
};

SR_ s_66[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR_ s_67[] =
{
    { { REQ_TOKEN}, {   3} },              
    { {       302}, { 103} }, // identifier
    { {       264}, {  41} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR_ s_68[] =
{
    { { REQ_DEF}, {   3} },              
    { {     262}, { 104} }, // DOT       
    { {     257}, { 105} }, // LEFT_PAREN
    { {       0}, { -76} },              
};

SR_ s_69[] =
{
    { { REQ_DEF}, {  22} },              
    { {     326}, { 106} }, // optExprL  
    { {     327}, { 107} }, // exprList  
    { {     309}, { 108} }, // expression
    { {     319}, {  24} }, // assignment
    { {     320}, {  25} }, // unary     
    { {     321}, {  26} }, // binary    
    { {     322}, {  27} }, // logical   
    { {     323}, {  28} }, // primary   
    { {     324}, {  29} }, // call      
    { {     302}, {  30} }, // identifier
    { {     294}, {  31} }, // BANG      
    { {     290}, {  32} }, // MINUS     
    { {     266}, {  33} }, // NUMBER    
    { {     265}, {  34} }, // STRING    
    { {     278}, {  35} }, // TRUE      
    { {     269}, {  36} }, // FALSE     
    { {     273}, {  37} }, // NIL       
    { {     257}, {  38} }, // LEFT_PAREN
    { {     277}, {  39} }, // THIS      
    { {     276}, {  40} }, // SUPER     
    { {     264}, {  41} }, // IDENTIFIER
    { {       0}, { -77} },              
};

SR_ s_70[] =
{
    { { REQ_TOKEN}, {   3} },              
    { {       302}, { 109} }, // identifier
    { {       264}, {  41} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR_ s_71[] =
{
    { { REQ_TOKEN}, {  20} },              
    { {       309}, { 110} }, // expression
    { {       319}, {  24} }, // assignment
    { {       320}, {  25} }, // unary     
    { {       321}, {  26} }, // binary    
    { {       322}, {  27} }, // logical   
    { {       323}, {  28} }, // primary   
    { {       324}, {  29} }, // call      
    { {       302}, {  30} }, // identifier
    { {       294}, {  31} }, // BANG      
    { {       290}, {  32} }, // MINUS     
    { {       266}, {  33} }, // NUMBER    
    { {       265}, {  34} }, // STRING    
    { {       278}, {  35} }, // TRUE      
    { {       269}, {  36} }, // FALSE     
    { {       273}, {  37} }, // NIL       
    { {       257}, {  38} }, // LEFT_PAREN
    { {       277}, {  39} }, // THIS      
    { {       276}, {  40} }, // SUPER     
    { {       264}, {  41} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR_ s_72[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -52} }, 
};

SR_ s_73[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -53} }, 
};

SR_ s_74[] =
{
    { { REQ_TOKEN}, {  14} },                 
    { {       258}, { 111} }, // RIGHT_PAREN  
    { {       285}, {  47} }, // EQUAL_EQUAL  
    { {       284}, {  48} }, // BANG_EQUAL   
    { {       288}, {  49} }, // LESS         
    { {       289}, {  50} }, // LESS_EQUAL   
    { {       286}, {  51} }, // GREATER      
    { {       287}, {  52} }, // GREATER_EQUAL
    { {       291}, {  53} }, // PLUS         
    { {       290}, {  54} }, // MINUS        
    { {       293}, {  55} }, // STAR         
    { {       292}, {  56} }, // SLASH        
    { {       282}, {  57} }, // OR           
    { {       283}, {  58} }, // AND          
    { {         0}, {   0} },                 
};

SR_ s_75[] =
{
    { { REQ_TOKEN}, {   3} },              
    { {       302}, { 112} }, // identifier
    { {       264}, {  41} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR_ s_76[] =
{
    { { REQ_DEF}, {   6} },              
    { {     303}, { 113} }, // optFunL   
    { {     304}, { 114} }, // funList   
    { {     305}, { 115} }, // function  
    { {     302}, {  44} }, // identifier
    { {     264}, {  41} }, // IDENTIFIER
    { {       0}, {  -9} },              
};

SR_ s_77[] =
{
    { { REQ_TOKEN}, {   3} },              
    { {       302}, { 116} }, // identifier
    { {       264}, {  41} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR_ s_78[] =
{
    { { REQ_DEF}, {   5} },              
    { {     306}, { 117} }, // optParamL 
    { {     308}, { 118} }, // paramList 
    { {     302}, { 119} }, // identifier
    { {     264}, {  41} }, // IDENTIFIER
    { {       0}, { -15} },              
};

SR_ s_79[] =
{
    { { REQ_TOKEN}, {  20} },              
    { {       309}, { 120} }, // expression
    { {       319}, {  24} }, // assignment
    { {       320}, {  25} }, // unary     
    { {       321}, {  26} }, // binary    
    { {       322}, {  27} }, // logical   
    { {       323}, {  28} }, // primary   
    { {       324}, {  29} }, // call      
    { {       302}, {  30} }, // identifier
    { {       294}, {  31} }, // BANG      
    { {       290}, {  32} }, // MINUS     
    { {       266}, {  33} }, // NUMBER    
    { {       265}, {  34} }, // STRING    
    { {       278}, {  35} }, // TRUE      
    { {       269}, {  36} }, // FALSE     
    { {       273}, {  37} }, // NIL       
    { {       257}, {  38} }, // LEFT_PAREN
    { {       277}, {  39} }, // THIS      
    { {       276}, {  40} }, // SUPER     
    { {       264}, {  41} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR_ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR_ s_81[] =
{
    { { REQ_DEF}, {   9} },                 
    { {     288}, {  49} }, // LESS         
    { {     289}, {  50} }, // LESS_EQUAL   
    { {     286}, {  51} }, // GREATER      
    { {     287}, {  52} }, // GREATER_EQUAL
    { {     291}, {  53} }, // PLUS         
    { {     290}, {  54} }, // MINUS        
    { {     293}, {  55} }, // STAR         
    { {     292}, {  56} }, // SLASH        
    { {       0}, { -54} },                 
};

SR_ s_82[] =
{
    { { REQ_DEF}, {   9} },                 
    { {     288}, {  49} }, // LESS         
    { {     289}, {  50} }, // LESS_EQUAL   
    { {     286}, {  51} }, // GREATER      
    { {     287}, {  52} }, // GREATER_EQUAL
    { {     291}, {  53} }, // PLUS         
    { {     290}, {  54} }, // MINUS        
    { {     293}, {  55} }, // STAR         
    { {     292}, {  56} }, // SLASH        
    { {       0}, { -55} },                 
};

SR_ s_83[] =
{
    { { REQ_DEF}, {   5} },         
    { {     291}, {  53} }, // PLUS 
    { {     290}, {  54} }, // MINUS
    { {     293}, {  55} }, // STAR 
    { {     292}, {  56} }, // SLASH
    { {       0}, { -56} },         
};

SR_ s_84[] =
{
    { { REQ_DEF}, {   5} },         
    { {     291}, {  53} }, // PLUS 
    { {     290}, {  54} }, // MINUS
    { {     293}, {  55} }, // STAR 
    { {     292}, {  56} }, // SLASH
    { {       0}, { -57} },         
};

SR_ s_85[] =
{
    { { REQ_DEF}, {   5} },         
    { {     291}, {  53} }, // PLUS 
    { {     290}, {  54} }, // MINUS
    { {     293}, {  55} }, // STAR 
    { {     292}, {  56} }, // SLASH
    { {       0}, { -58} },         
};

SR_ s_86[] =
{
    { { REQ_DEF}, {   5} },         
    { {     291}, {  53} }, // PLUS 
    { {     290}, {  54} }, // MINUS
    { {     293}, {  55} }, // STAR 
    { {     292}, {  56} }, // SLASH
    { {       0}, { -59} },         
};

SR_ s_87[] =
{
    { { REQ_DEF}, {   3} },         
    { {     293}, {  55} }, // STAR 
    { {     292}, {  56} }, // SLASH
    { {       0}, { -60} },         
};

SR_ s_88[] =
{
    { { REQ_DEF}, {   3} },         
    { {     293}, {  55} }, // STAR 
    { {     292}, {  56} }, // SLASH
    { {       0}, { -61} },         
};

SR_ s_89[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -62} }, 
};

SR_ s_90[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -63} }, 
};

SR_ s_91[] =
{
    { { REQ_DEF}, {  12} },                 
    { {     285}, {  47} }, // EQUAL_EQUAL  
    { {     284}, {  48} }, // BANG_EQUAL   
    { {     288}, {  49} }, // LESS         
    { {     289}, {  50} }, // LESS_EQUAL   
    { {     286}, {  51} }, // GREATER      
    { {     287}, {  52} }, // GREATER_EQUAL
    { {     291}, {  53} }, // PLUS         
    { {     290}, {  54} }, // MINUS        
    { {     293}, {  55} }, // STAR         
    { {     292}, {  56} }, // SLASH        
    { {     283}, {  58} }, // AND          
    { {       0}, { -64} },                 
};

SR_ s_92[] =
{
    { { REQ_DEF}, {  11} },                 
    { {     285}, {  47} }, // EQUAL_EQUAL  
    { {     284}, {  48} }, // BANG_EQUAL   
    { {     288}, {  49} }, // LESS         
    { {     289}, {  50} }, // LESS_EQUAL   
    { {     286}, {  51} }, // GREATER      
    { {     287}, {  52} }, // GREATER_EQUAL
    { {     291}, {  53} }, // PLUS         
    { {     290}, {  54} }, // MINUS        
    { {     293}, {  55} }, // STAR         
    { {     292}, {  56} }, // SLASH        
    { {       0}, { -65} },                 
};

SR_ s_93[] =
{
    { { REQ_DEF}, {  21} },              
    { {     317}, { 121} }, // optExpr   
    { {     309}, {  63} }, // expression
    { {     319}, {  24} }, // assignment
    { {     320}, {  25} }, // unary     
    { {     321}, {  26} }, // binary    
    { {     322}, {  27} }, // logical   
    { {     323}, {  28} }, // primary   
    { {     324}, {  29} }, // call      
    { {     302}, {  30} }, // identifier
    { {     294}, {  31} }, // BANG      
    { {     290}, {  32} }, // MINUS     
    { {     266}, {  33} }, // NUMBER    
    { {     265}, {  34} }, // STRING    
    { {     278}, {  35} }, // TRUE      
    { {     269}, {  36} }, // FALSE     
    { {     273}, {  37} }, // NIL       
    { {     257}, {  38} }, // LEFT_PAREN
    { {     277}, {  39} }, // THIS      
    { {     276}, {  40} }, // SUPER     
    { {     264}, {  41} }, // IDENTIFIER
    { {       0}, { -41} },              
};

SR_ s_94[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR_ s_95[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR_ s_96[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR_ s_97[] =
{
    { { REQ_TOKEN}, {  14} },                 
    { {       258}, { 122} }, // RIGHT_PAREN  
    { {       285}, {  47} }, // EQUAL_EQUAL  
    { {       284}, {  48} }, // BANG_EQUAL   
    { {       288}, {  49} }, // LESS         
    { {       289}, {  50} }, // LESS_EQUAL   
    { {       286}, {  51} }, // GREATER      
    { {       287}, {  52} }, // GREATER_EQUAL
    { {       291}, {  53} }, // PLUS         
    { {       290}, {  54} }, // MINUS        
    { {       293}, {  55} }, // STAR         
    { {       292}, {  56} }, // SLASH        
    { {       282}, {  57} }, // OR           
    { {       283}, {  58} }, // AND          
    { {         0}, {   0} },                 
};

SR_ s_98[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR_ s_99[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR_ s_100[] =
{
    { { REQ_TOKEN}, {  14} },                 
    { {       258}, { 123} }, // RIGHT_PAREN  
    { {       285}, {  47} }, // EQUAL_EQUAL  
    { {       284}, {  48} }, // BANG_EQUAL   
    { {       288}, {  49} }, // LESS         
    { {       289}, {  50} }, // LESS_EQUAL   
    { {       286}, {  51} }, // GREATER      
    { {       287}, {  52} }, // GREATER_EQUAL
    { {       291}, {  53} }, // PLUS         
    { {       290}, {  54} }, // MINUS        
    { {       293}, {  55} }, // STAR         
    { {       292}, {  56} }, // SLASH        
    { {       282}, {  57} }, // OR           
    { {       283}, {  58} }, // AND          
    { {         0}, {   0} },                 
};

SR_ s_101[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR_ s_102[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR_ s_103[] =
{
    { { REQ_DEF}, {   2} },         
    { {     281}, { 124} }, // EQUAL
    { {       0}, { -83} },         
};

SR_ s_104[] =
{
    { { REQ_TOKEN}, {   3} },              
    { {       302}, { 125} }, // identifier
    { {       264}, {  41} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR_ s_105[] =
{
    { { REQ_DEF}, {  22} },              
    { {     326}, { 126} }, // optExprL  
    { {     327}, { 107} }, // exprList  
    { {     309}, { 108} }, // expression
    { {     319}, {  24} }, // assignment
    { {     320}, {  25} }, // unary     
    { {     321}, {  26} }, // binary    
    { {     322}, {  27} }, // logical   
    { {     323}, {  28} }, // primary   
    { {     324}, {  29} }, // call      
    { {     302}, {  30} }, // identifier
    { {     294}, {  31} }, // BANG      
    { {     290}, {  32} }, // MINUS     
    { {     266}, {  33} }, // NUMBER    
    { {     265}, {  34} }, // STRING    
    { {     278}, {  35} }, // TRUE      
    { {     269}, {  36} }, // FALSE     
    { {     273}, {  37} }, // NIL       
    { {     257}, {  38} }, // LEFT_PAREN
    { {     277}, {  39} }, // THIS      
    { {     276}, {  40} }, // SUPER     
    { {     264}, {  41} }, // IDENTIFIER
    { {       0}, { -77} },              
};

SR_ s_106[] =
{
    { { REQ_TOKEN}, {   2} },               
    { {       258}, { 127} }, // RIGHT_PAREN
    { {         0}, {   0} },               
};

SR_ s_107[] =
{
    { { REQ_DEF}, {   2} },         
    { {     261}, { 128} }, // COMMA
    { {       0}, { -78} },         
};

SR_ s_108[] =
{
    { { REQ_DEF}, {  13} },                 
    { {     285}, {  47} }, // EQUAL_EQUAL  
    { {     284}, {  48} }, // BANG_EQUAL   
    { {     288}, {  49} }, // LESS         
    { {     289}, {  50} }, // LESS_EQUAL   
    { {     286}, {  51} }, // GREATER      
    { {     287}, {  52} }, // GREATER_EQUAL
    { {     291}, {  53} }, // PLUS         
    { {     290}, {  54} }, // MINUS        
    { {     293}, {  55} }, // STAR         
    { {     292}, {  56} }, // SLASH        
    { {     282}, {  57} }, // OR           
    { {     283}, {  58} }, // AND          
    { {       0}, { -80} },                 
};

SR_ s_109[] =
{
    { { REQ_TOKEN}, {   2} },         
    { {       281}, { 129} }, // EQUAL
    { {         0}, {   0} },         
};

SR_ s_110[] =
{
    { { REQ_DEF}, {  13} },                 
    { {     285}, {  47} }, // EQUAL_EQUAL  
    { {     284}, {  48} }, // BANG_EQUAL   
    { {     288}, {  49} }, // LESS         
    { {     289}, {  50} }, // LESS_EQUAL   
    { {     286}, {  51} }, // GREATER      
    { {     287}, {  52} }, // GREATER_EQUAL
    { {     291}, {  53} }, // PLUS         
    { {     290}, {  54} }, // MINUS        
    { {     293}, {  55} }, // STAR         
    { {     292}, {  56} }, // SLASH        
    { {     282}, {  57} }, // OR           
    { {     283}, {  58} }, // AND          
    { {       0}, { -49} },                 
};

SR_ s_111[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -72} }, 
};

SR_ s_112[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -74} }, 
};

SR_ s_113[] =
{
    { { REQ_TOKEN}, {   2} },               
    { {       260}, { 130} }, // RIGHT_BRACE
    { {         0}, {   0} },               
};

SR_ s_114[] =
{
    { { REQ_DEF}, {   4} },              
    { {     305}, { 131} }, // function  
    { {     302}, {  44} }, // identifier
    { {     264}, {  41} }, // IDENTIFIER
    { {       0}, { -10} },              
};

SR_ s_115[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR_ s_116[] =
{
    { { REQ_TOKEN}, {   2} },              
    { {       259}, { 132} }, // LEFT_BRACE
    { {         0}, {   0} },              
};

SR_ s_117[] =
{
    { { REQ_TOKEN}, {   2} },               
    { {       258}, { 133} }, // RIGHT_PAREN
    { {         0}, {   0} },               
};

SR_ s_118[] =
{
    { { REQ_DEF}, {   2} },         
    { {     261}, { 134} }, // COMMA
    { {       0}, { -16} },         
};

SR_ s_119[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR_ s_120[] =
{
    { { REQ_TOKEN}, {  14} },                 
    { {       263}, { 135} }, // SEMICOLON    
    { {       285}, {  47} }, // EQUAL_EQUAL  
    { {       284}, {  48} }, // BANG_EQUAL   
    { {       288}, {  49} }, // LESS         
    { {       289}, {  50} }, // LESS_EQUAL   
    { {       286}, {  51} }, // GREATER      
    { {       287}, {  52} }, // GREATER_EQUAL
    { {       291}, {  53} }, // PLUS         
    { {       290}, {  54} }, // MINUS        
    { {       293}, {  55} }, // STAR         
    { {       292}, {  56} }, // SLASH        
    { {       282}, {  57} }, // OR           
    { {       283}, {  58} }, // AND          
    { {         0}, {   0} },                 
};

SR_ s_121[] =
{
    { { REQ_TOKEN}, {   2} },             
    { {       263}, { 136} }, // SEMICOLON
    { {         0}, {   0} },             
};

SR_ s_122[] =
{
    { { REQ_TOKEN}, {  34} },              
    { {       301}, { 137} }, // statement 
    { {       310}, {  10} }, // exprStmt  
    { {       311}, {  11} }, // forStmt   
    { {       312}, {  12} }, // ifStmt    
    { {       313}, {  13} }, // printStmt 
    { {       314}, {  14} }, // returnStmt
    { {       315}, {  15} }, // whileStmt 
    { {       307}, {  16} }, // block     
    { {       309}, {  17} }, // expression
    { {       271}, {  18} }, // FOR       
    { {       272}, {  19} }, // IF        
    { {       274}, {  20} }, // PRINT     
    { {       275}, {  21} }, // RETURN    
    { {       280}, {  22} }, // WHILE     
    { {       259}, {  23} }, // LEFT_BRACE
    { {       319}, {  24} }, // assignment
    { {       320}, {  25} }, // unary     
    { {       321}, {  26} }, // binary    
    { {       322}, {  27} }, // logical   
    { {       323}, {  28} }, // primary   
    { {       324}, {  29} }, // call      
    { {       302}, {  30} }, // identifier
    { {       294}, {  31} }, // BANG      
    { {       290}, {  32} }, // MINUS     
    { {       266}, {  33} }, // NUMBER    
    { {       265}, {  34} }, // STRING    
    { {       278}, {  35} }, // TRUE      
    { {       269}, {  36} }, // FALSE     
    { {       273}, {  37} }, // NIL       
    { {       257}, {  38} }, // LEFT_PAREN
    { {       277}, {  39} }, // THIS      
    { {       276}, {  40} }, // SUPER     
    { {       264}, {  41} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR_ s_123[] =
{
    { { REQ_TOKEN}, {  34} },              
    { {       301}, { 138} }, // statement 
    { {       310}, {  10} }, // exprStmt  
    { {       311}, {  11} }, // forStmt   
    { {       312}, {  12} }, // ifStmt    
    { {       313}, {  13} }, // printStmt 
    { {       314}, {  14} }, // returnStmt
    { {       315}, {  15} }, // whileStmt 
    { {       307}, {  16} }, // block     
    { {       309}, {  17} }, // expression
    { {       271}, {  18} }, // FOR       
    { {       272}, {  19} }, // IF        
    { {       274}, {  20} }, // PRINT     
    { {       275}, {  21} }, // RETURN    
    { {       280}, {  22} }, // WHILE     
    { {       259}, {  23} }, // LEFT_BRACE
    { {       319}, {  24} }, // assignment
    { {       320}, {  25} }, // unary     
    { {       321}, {  26} }, // binary    
    { {       322}, {  27} }, // logical   
    { {       323}, {  28} }, // primary   
    { {       324}, {  29} }, // call      
    { {       302}, {  30} }, // identifier
    { {       294}, {  31} }, // BANG      
    { {       290}, {  32} }, // MINUS     
    { {       266}, {  33} }, // NUMBER    
    { {       265}, {  34} }, // STRING    
    { {       278}, {  35} }, // TRUE      
    { {       269}, {  36} }, // FALSE     
    { {       273}, {  37} }, // NIL       
    { {       257}, {  38} }, // LEFT_PAREN
    { {       277}, {  39} }, // THIS      
    { {       276}, {  40} }, // SUPER     
    { {       264}, {  41} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR_ s_124[] =
{
    { { REQ_TOKEN}, {  20} },              
    { {       309}, { 139} }, // expression
    { {       319}, {  24} }, // assignment
    { {       320}, {  25} }, // unary     
    { {       321}, {  26} }, // binary    
    { {       322}, {  27} }, // logical   
    { {       323}, {  28} }, // primary   
    { {       324}, {  29} }, // call      
    { {       302}, {  30} }, // identifier
    { {       294}, {  31} }, // BANG      
    { {       290}, {  32} }, // MINUS     
    { {       266}, {  33} }, // NUMBER    
    { {       265}, {  34} }, // STRING    
    { {       278}, {  35} }, // TRUE      
    { {       269}, {  36} }, // FALSE     
    { {       273}, {  37} }, // NIL       
    { {       257}, {  38} }, // LEFT_PAREN
    { {       277}, {  39} }, // THIS      
    { {       276}, {  40} }, // SUPER     
    { {       264}, {  41} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR_ s_125[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -81} }, 
};

SR_ s_126[] =
{
    { { REQ_TOKEN}, {   2} },               
    { {       258}, { 140} }, // RIGHT_PAREN
    { {         0}, {   0} },               
};

SR_ s_127[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -84} }, 
};

SR_ s_128[] =
{
    { { REQ_TOKEN}, {  20} },              
    { {       309}, { 141} }, // expression
    { {       319}, {  24} }, // assignment
    { {       320}, {  25} }, // unary     
    { {       321}, {  26} }, // binary    
    { {       322}, {  27} }, // logical   
    { {       323}, {  28} }, // primary   
    { {       324}, {  29} }, // call      
    { {       302}, {  30} }, // identifier
    { {       294}, {  31} }, // BANG      
    { {       290}, {  32} }, // MINUS     
    { {       266}, {  33} }, // NUMBER    
    { {       265}, {  34} }, // STRING    
    { {       278}, {  35} }, // TRUE      
    { {       269}, {  36} }, // FALSE     
    { {       273}, {  37} }, // NIL       
    { {       257}, {  38} }, // LEFT_PAREN
    { {       277}, {  39} }, // THIS      
    { {       276}, {  40} }, // SUPER     
    { {       264}, {  41} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR_ s_129[] =
{
    { { REQ_TOKEN}, {  20} },              
    { {       309}, { 142} }, // expression
    { {       319}, {  24} }, // assignment
    { {       320}, {  25} }, // unary     
    { {       321}, {  26} }, // binary    
    { {       322}, {  27} }, // logical   
    { {       323}, {  28} }, // primary   
    { {       324}, {  29} }, // call      
    { {       302}, {  30} }, // identifier
    { {       294}, {  31} }, // BANG      
    { {       290}, {  32} }, // MINUS     
    { {       266}, {  33} }, // NUMBER    
    { {       265}, {  34} }, // STRING    
    { {       278}, {  35} }, // TRUE      
    { {       269}, {  36} }, // FALSE     
    { {       273}, {  37} }, // NIL       
    { {       257}, {  38} }, // LEFT_PAREN
    { {       277}, {  39} }, // THIS      
    { {       276}, {  40} }, // SUPER     
    { {       264}, {  41} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR_ s_130[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR_ s_131[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR_ s_132[] =
{
    { { REQ_DEF}, {   6} },              
    { {     303}, { 143} }, // optFunL   
    { {     304}, { 114} }, // funList   
    { {     305}, { 115} }, // function  
    { {     302}, {  44} }, // identifier
    { {     264}, {  41} }, // IDENTIFIER
    { {       0}, {  -9} },              
};

SR_ s_133[] =
{
    { { REQ_TOKEN}, {   3} },              
    { {       307}, { 144} }, // block     
    { {       259}, {  23} }, // LEFT_BRACE
    { {         0}, {   0} },              
};

SR_ s_134[] =
{
    { { REQ_TOKEN}, {   3} },              
    { {       302}, { 145} }, // identifier
    { {       264}, {  41} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR_ s_135[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR_ s_136[] =
{
    { { REQ_DEF}, {  21} },              
    { {     317}, { 146} }, // optExpr   
    { {     309}, {  63} }, // expression
    { {     319}, {  24} }, // assignment
    { {     320}, {  25} }, // unary     
    { {     321}, {  26} }, // binary    
    { {     322}, {  27} }, // logical   
    { {     323}, {  28} }, // primary   
    { {     324}, {  29} }, // call      
    { {     302}, {  30} }, // identifier
    { {     294}, {  31} }, // BANG      
    { {     290}, {  32} }, // MINUS     
    { {     266}, {  33} }, // NUMBER    
    { {     265}, {  34} }, // STRING    
    { {     278}, {  35} }, // TRUE      
    { {     269}, {  36} }, // FALSE     
    { {     273}, {  37} }, // NIL       
    { {     257}, {  38} }, // LEFT_PAREN
    { {     277}, {  39} }, // THIS      
    { {     276}, {  40} }, // SUPER     
    { {     264}, {  41} }, // IDENTIFIER
    { {       0}, { -41} },              
};

SR_ s_137[] =
{
    { { REQ_DEF}, {   2} },        
    { {     268}, { 147} }, // ELSE
    { {       0}, { -34} },        
};

SR_ s_138[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR_ s_139[] =
{
    { { REQ_DEF}, {  13} },                 
    { {     285}, {  47} }, // EQUAL_EQUAL  
    { {     284}, {  48} }, // BANG_EQUAL   
    { {     288}, {  49} }, // LESS         
    { {     289}, {  50} }, // LESS_EQUAL   
    { {     286}, {  51} }, // GREATER      
    { {     287}, {  52} }, // GREATER_EQUAL
    { {     291}, {  53} }, // PLUS         
    { {     290}, {  54} }, // MINUS        
    { {     293}, {  55} }, // STAR         
    { {     292}, {  56} }, // SLASH        
    { {     282}, {  57} }, // OR           
    { {     283}, {  58} }, // AND          
    { {       0}, { -50} },                 
};

SR_ s_140[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -82} }, 
};

SR_ s_141[] =
{
    { { REQ_DEF}, {  13} },                 
    { {     285}, {  47} }, // EQUAL_EQUAL  
    { {     284}, {  48} }, // BANG_EQUAL   
    { {     288}, {  49} }, // LESS         
    { {     289}, {  50} }, // LESS_EQUAL   
    { {     286}, {  51} }, // GREATER      
    { {     287}, {  52} }, // GREATER_EQUAL
    { {     291}, {  53} }, // PLUS         
    { {     290}, {  54} }, // MINUS        
    { {     293}, {  55} }, // STAR         
    { {     292}, {  56} }, // SLASH        
    { {     282}, {  57} }, // OR           
    { {     283}, {  58} }, // AND          
    { {       0}, { -79} },                 
};

SR_ s_142[] =
{
    { { REQ_DEF}, {  13} },                 
    { {     285}, {  47} }, // EQUAL_EQUAL  
    { {     284}, {  48} }, // BANG_EQUAL   
    { {     288}, {  49} }, // LESS         
    { {     289}, {  50} }, // LESS_EQUAL   
    { {     286}, {  51} }, // GREATER      
    { {     287}, {  52} }, // GREATER_EQUAL
    { {     291}, {  53} }, // PLUS         
    { {     290}, {  54} }, // MINUS        
    { {     293}, {  55} }, // STAR         
    { {     292}, {  56} }, // SLASH        
    { {     282}, {  57} }, // OR           
    { {     283}, {  58} }, // AND          
    { {       0}, { -51} },                 
};

SR_ s_143[] =
{
    { { REQ_TOKEN}, {   2} },               
    { {       260}, { 148} }, // RIGHT_BRACE
    { {         0}, {   0} },               
};

SR_ s_144[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR_ s_145[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR_ s_146[] =
{
    { { REQ_TOKEN}, {   2} },               
    { {       258}, { 149} }, // RIGHT_PAREN
    { {         0}, {   0} },               
};

SR_ s_147[] =
{
    { { REQ_TOKEN}, {  34} },              
    { {       301}, { 150} }, // statement 
    { {       310}, {  10} }, // exprStmt  
    { {       311}, {  11} }, // forStmt   
    { {       312}, {  12} }, // ifStmt    
    { {       313}, {  13} }, // printStmt 
    { {       314}, {  14} }, // returnStmt
    { {       315}, {  15} }, // whileStmt 
    { {       307}, {  16} }, // block     
    { {       309}, {  17} }, // expression
    { {       271}, {  18} }, // FOR       
    { {       272}, {  19} }, // IF        
    { {       274}, {  20} }, // PRINT     
    { {       275}, {  21} }, // RETURN    
    { {       280}, {  22} }, // WHILE     
    { {       259}, {  23} }, // LEFT_BRACE
    { {       319}, {  24} }, // assignment
    { {       320}, {  25} }, // unary     
    { {       321}, {  26} }, // binary    
    { {       322}, {  27} }, // logical   
    { {       323}, {  28} }, // primary   
    { {       324}, {  29} }, // call      
    { {       302}, {  30} }, // identifier
    { {       294}, {  31} }, // BANG      
    { {       290}, {  32} }, // MINUS     
    { {       266}, {  33} }, // NUMBER    
    { {       265}, {  34} }, // STRING    
    { {       278}, {  35} }, // TRUE      
    { {       269}, {  36} }, // FALSE     
    { {       273}, {  37} }, // NIL       
    { {       257}, {  38} }, // LEFT_PAREN
    { {       277}, {  39} }, // THIS      
    { {       276}, {  40} }, // SUPER     
    { {       264}, {  41} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR_ s_148[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR_ s_149[] =
{
    { { REQ_TOKEN}, {  34} },              
    { {       301}, { 151} }, // statement 
    { {       310}, {  10} }, // exprStmt  
    { {       311}, {  11} }, // forStmt   
    { {       312}, {  12} }, // ifStmt    
    { {       313}, {  13} }, // printStmt 
    { {       314}, {  14} }, // returnStmt
    { {       315}, {  15} }, // whileStmt 
    { {       307}, {  16} }, // block     
    { {       309}, {  17} }, // expression
    { {       271}, {  18} }, // FOR       
    { {       272}, {  19} }, // IF        
    { {       274}, {  20} }, // PRINT     
    { {       275}, {  21} }, // RETURN    
    { {       280}, {  22} }, // WHILE     
    { {       259}, {  23} }, // LEFT_BRACE
    { {       319}, {  24} }, // assignment
    { {       320}, {  25} }, // unary     
    { {       321}, {  26} }, // binary    
    { {       322}, {  27} }, // logical   
    { {       323}, {  28} }, // primary   
    { {       324}, {  29} }, // call      
    { {       302}, {  30} }, // identifier
    { {       294}, {  31} }, // BANG      
    { {       290}, {  32} }, // MINUS     
    { {       266}, {  33} }, // NUMBER    
    { {       265}, {  34} }, // STRING    
    { {       278}, {  35} }, // TRUE      
    { {       269}, {  36} }, // FALSE     
    { {       273}, {  37} }, // NIL       
    { {       257}, {  38} }, // LEFT_PAREN
    { {       277}, {  39} }, // THIS      
    { {       276}, {  40} }, // SUPER     
    { {       264}, {  41} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR_ s_150[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR_ s_151[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};


// State array:
SR_ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,  s_136,  s_137,  s_138,  s_139,
  s_140,  s_141,  s_142,  s_143,  s_144,  s_145,  s_146,  s_147,  s_148,  s_149,
  s_150,  s_151,
};

} // anonymous namespace ends




// If the parsing function call (i.e., parse()' needs arguments, then provide
// an overloaded function.  The code below doesn't rely on parameters, so no
// arguments are required.  Furthermore, parse uses a function try block to
// allow us to do ACCEPT and ABORT from anywhere, even from within members
// called by actions, simply throwing the appropriate exceptions.


// base/base1
LoxgramBase::LoxgramBase()
:
    d_token(Reserved_::UNDETERMINED_),
    // $insert baseclasscode
    d_requiredTokens_(0)
{
}

// base/clearin
void LoxgramBase::clearin_()
{
    d_nErrors_ = 0;
    d_stackIdx = -1;
    d_stateStack.clear();
    d_token = Reserved_::UNDETERMINED_;
    d_next = TokenPair{ Reserved_::UNDETERMINED_, STYPE_{} };
    d_recovery = false;
    d_acceptedTokens_ = d_requiredTokens_;
    d_val_ = STYPE_{};

    push_(0);
}

// base/debugfunctions

void LoxgramBase::setDebug(bool mode)
{
    d_actionCases_ = false;
    d_debug_ = mode;
}

void LoxgramBase::setDebug(DebugMode_ mode)
{
    d_actionCases_ = mode & ACTIONCASES;
    d_debug_ =       mode & ON;
}

// base/lex
void LoxgramBase::lex_(int token)
{
    d_token = token;

    if (d_token <= 0)
        d_token = Reserved_::EOF_;

    d_terminalToken = true;
}

// base/lookup
int LoxgramBase::lookup_() const
{
    // if the final transition is negative, then we should reduce by the rule
    // given by its positive value.

    SR_ const *sr = s_state[d_state];
    SR_ const *last = sr + sr->d_lastIdx;

    for ( ; ++sr != last; )           // visit all but the last SR entries
    {
        if (sr->d_token == d_token)
            return sr->d_action;
    }

    if (sr == last)   // reached the last element
    {
        if (sr->d_action < 0)   // default reduction
        {
            return sr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN_;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = sr->d_action;


    return action;
}

// base/pop
void LoxgramBase::pop_(size_t count)
{
    if (d_stackIdx < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx -= count;
    d_state = d_stateStack[d_stackIdx].first;
    d_vsp = &d_stateStack[d_stackIdx];

}

// base/poptoken
void LoxgramBase::popToken_()
{
    d_token = d_next.first;
    d_val_ = std::move(d_next.second);

    d_next.first = Reserved_::UNDETERMINED_;
}

// base/push
void LoxgramBase::push_(size_t state)
{
    size_t currentSize = d_stateStack.size();
    if (stackSize_() == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION_;
        d_stateStack.resize(newSize);
    }

    ++d_stackIdx;
    d_stateStack[d_stackIdx] = 
                    StatePair{ d_state = state, std::move(d_val_) };

    d_vsp = &d_stateStack[d_stackIdx];

    if (d_stackIdx == 0)
    {
    }
    else
    {
    }
}

// base/pushtoken
void LoxgramBase::pushToken_(int token)
{
    d_next = TokenPair{ d_token, std::move(d_val_) };
    d_token = token;
}

// base/redotoken
void LoxgramBase::redoToken_()
{
    if (d_token != Reserved_::UNDETERMINED_)
        pushToken_(d_token);
}

// base/reduce
void LoxgramBase::reduce_(int rule)
{
    PI_ const &pi = s_productionInfo[rule];

    d_token = pi.d_nonTerm;
    pop_(pi.d_size);

    d_terminalToken = false;
}

// base/shift
void LoxgramBase::shift_(int action)
{
    push_(action);
    popToken_();               // token processed

    if (d_recovery and d_terminalToken)
    {
        d_recovery = false;
        d_acceptedTokens_ = 0;
    }
}

// base/startrecovery
void LoxgramBase::startRecovery_()
{
    int lastToken = d_token;                // give the unexpected token a
                                            // chance to be processed
                                            // again.

    pushToken_(Reserved_::errTok_);      // specify errTok_ as next token
    push_(lookup_());                     // push the error state

    d_token = lastToken;                    // reactivate the unexpected
                                            // token (we're now in an
                                            // ERROR state).

    d_recovery = true;
}

// base/top
inline size_t LoxgramBase::top_() const
{
    return d_stateStack[d_stackIdx].first;
}

// derived/errorrecovery
void Loxgram::errorRecovery_()
{
    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)



    if (d_acceptedTokens_ >= d_requiredTokens_)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors_;                          // were accepted. Otherwise
        error();                                // simply skip input
    }

    // get the error state
    while (not (s_state[top_()][0].d_type & ERR_ITEM))
    {
        pop_();
    }

    // In the error state, looking up a token allows us to proceed.
    // Continuation may be require multiple reductions, but eventually a
    // terminal-token shift is used. See nextCycle_ for details.

    startRecovery_();
}

// derived/executeaction
void Loxgram::executeAction_(int production)
try
{
    if (token_() != Reserved_::UNDETERMINED_)
        pushToken_(token_());     // save an already available token
    switch (production)
    {
        // $insert actioncases
        
        case 2:
#line 30 "loxgram"
        { if (action_stmt) (*action_stmt)(std::dynamic_pointer_cast<Stmt>(vs_(0))); }
        break;

        case 3:
#line 34 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 4:
#line 35 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 5:
#line 36 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 6:
#line 37 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 7:
#line 39 "loxgram"
        { d_val_ = vs_(-1); std::dynamic_pointer_cast<StmtClass>(d_val_)->setName(get<std::string>(std::dynamic_pointer_cast<ExprLiteral>(vs_(-3))->get())); }
        break;

        case 8:
#line 40 "loxgram"
        { d_val_ = vs_(-1); std::dynamic_pointer_cast<StmtClass>(d_val_)->setName(get<std::string>(std::dynamic_pointer_cast<ExprLiteral>(vs_(-5))->get())); std::dynamic_pointer_cast<StmtClass>(d_val_)->setSuper(std::make_shared<ExprVariable>(get<std::string>(std::dynamic_pointer_cast<ExprLiteral>(vs_(-3))->get()))); }
        break;

        case 9:
#line 43 "loxgram"
        { d_val_ = std::make_shared<StmtClass>(); }
        break;

        case 10:
#line 45 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 11:
#line 47 "loxgram"
        { d_val_ = vs_(-1); std::dynamic_pointer_cast<StmtClass>(d_val_)->addMethod(std::dynamic_pointer_cast<StmtFunction>(vs_(-1))); }
        break;

        case 12:
#line 48 "loxgram"
        { d_val_ = std::make_shared<StmtClass>(); std::dynamic_pointer_cast<StmtClass>(d_val_)->addMethod(std::dynamic_pointer_cast<StmtFunction>(vs_(0))); }
        break;

        case 13:
#line 51 "loxgram"
        { d_val_ = vs_(-2); std::dynamic_pointer_cast<StmtFunction>(d_val_)->setName(get<std::string>(std::dynamic_pointer_cast<ExprLiteral>(vs_(-4))->get())); std::dynamic_pointer_cast<StmtFunction>(d_val_)->setBody(std::dynamic_pointer_cast<StmtBlock>(vs_(0))); }
        break;

        case 14:
#line 54 "loxgram"
        { d_val_ = vs_(0); }
        break;

        case 15:
#line 57 "loxgram"
        { d_val_ = std::make_shared<StmtFunction>(); }
        break;

        case 16:
#line 59 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 17:
#line 61 "loxgram"
        { d_val_ = vs_(-2); std::dynamic_pointer_cast<StmtFunction>(d_val_)->addParam(get<std::string>(std::dynamic_pointer_cast<ExprLiteral>(vs_(0))->get())); }
        break;

        case 18:
#line 62 "loxgram"
        { d_val_ = std::make_shared<StmtFunction>(); std::dynamic_pointer_cast<StmtFunction>(d_val_)->addParam(get<std::string>(std::dynamic_pointer_cast<ExprLiteral>(vs_(0))->get())); }
        break;

        case 19:
#line 65 "loxgram"
        { d_val_ = std::make_shared<StmtVariable>(get<std::string>(std::dynamic_pointer_cast<ExprLiteral>(vs_(-3))->get()), std::dynamic_pointer_cast<Expr>(vs_(-1))); }
        break;

        case 20:
#line 66 "loxgram"
        { d_val_ = std::make_shared<StmtVariable>(get<std::string>(std::dynamic_pointer_cast<ExprLiteral>(vs_(-1))->get()), std::make_shared<ExprLiteral>(std::monostate{})); }
        break;

        case 21:
#line 70 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 22:
#line 71 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 23:
#line 72 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 24:
#line 73 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 25:
#line 74 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 26:
#line 75 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 27:
#line 76 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 28:
#line 78 "loxgram"
        { d_val_ = vs_(-1); }
        break;

        case 29:
#line 81 "loxgram"
        { d_val_ = vs_(-1); std::dynamic_pointer_cast<StmtBlock>(d_val_)->append(std::dynamic_pointer_cast<Stmt>(vs_(0))); }
        break;

        case 30:
#line 82 "loxgram"
        { d_val_ = std::make_shared<StmtBlock>(); std::dynamic_pointer_cast<StmtBlock>(d_val_)->append(std::dynamic_pointer_cast<Stmt>(vs_(0))); }
        break;

        case 31:
#line 85 "loxgram"
        { d_val_ = std::make_shared<StmtExpression>(std::dynamic_pointer_cast<Expr>(vs_(-1))); }
        break;

        case 32:
#line 88 "loxgram"
        { d_val_ = std::make_shared<StmtPrint>(std::dynamic_pointer_cast<Expr>(vs_(-1))); }
        break;

        case 33:
#line 91 "loxgram"
        { d_val_ = std::make_shared<StmtReturn>(vs_(-1) ? std::dynamic_pointer_cast<Expr>(vs_(-1)) : std::make_shared<ExprLiteral>(std::monostate{})); }
        break;

        case 34:
#line 94 "loxgram"
        { d_val_ = std::make_shared<StmtIf>(std::dynamic_pointer_cast<Expr>(vs_(-2)), std::dynamic_pointer_cast<Stmt>(vs_(0)), nullptr); }
        break;

        case 35:
#line 95 "loxgram"
        { d_val_ = std::make_shared<StmtIf>(std::dynamic_pointer_cast<Expr>(vs_(-4)), std::dynamic_pointer_cast<Stmt>(vs_(-2)), std::dynamic_pointer_cast<Stmt>(vs_(0))); }
        break;

        case 36:
#line 98 "loxgram"
        { d_val_ = std::make_shared<StmtWhile>(std::dynamic_pointer_cast<Expr>(vs_(-2)), std::dynamic_pointer_cast<Stmt>(vs_(0))); }
        break;

        case 37:
#line 101 "loxgram"
        {
         auto outerBlock = std::make_shared<StmtBlock>(); outerBlock->append(std::dynamic_pointer_cast<Stmt>(vs_(-5)));
         auto innerBlock = std::make_shared<StmtBlock>(); innerBlock->append(std::dynamic_pointer_cast<Stmt>(vs_(0)));
         if (vs_(-2)) {
         innerBlock->append(std::make_shared<StmtExpression>(std::dynamic_pointer_cast<Expr>(vs_(-2))));
         }
         outerBlock->append(std::make_shared<StmtWhile>(vs_(-4) ? std::dynamic_pointer_cast<Expr>(vs_(-4)) : std::make_shared<ExprLiteral>(true), innerBlock));
         d_val_ = outerBlock;
         }
        break;

        case 38:
#line 112 "loxgram"
        { d_val_ = nullptr; }
        break;

        case 39:
#line 114 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 40:
#line 115 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 41:
#line 117 "loxgram"
        { d_val_ = nullptr; }
        break;

        case 42:
#line 119 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 43:
#line 122 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 44:
#line 123 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 45:
#line 124 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 46:
#line 125 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 47:
#line 126 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 48:
#line 127 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 49:
#line 129 "loxgram"
        { d_val_ = std::make_shared<ExprAssign>(get<std::string>(std::dynamic_pointer_cast<ExprLiteral>(vs_(-2))->get()), std::dynamic_pointer_cast<Expr>(vs_(0))); }
        break;

        case 50:
#line 130 "loxgram"
        { d_val_ = std::make_shared<ExprSet>(std::dynamic_pointer_cast<Expr>(vs_(-4)), get<std::string>(std::dynamic_pointer_cast<ExprLiteral>(vs_(-2))->get()), std::dynamic_pointer_cast<Expr>(vs_(0))); }
        break;

        case 51:
#line 131 "loxgram"
        { d_val_ = std::make_shared<ExprSet>(std::dynamic_pointer_cast<Expr>(vs_(-4)), get<std::string>(std::dynamic_pointer_cast<ExprLiteral>(vs_(-2))->get()), std::dynamic_pointer_cast<Expr>(vs_(0))); }
        break;

        case 52:
#line 134 "loxgram"
        { d_val_ = std::make_shared<ExprUnary>(BANG, std::dynamic_pointer_cast<Expr>(vs_(0))); }
        break;

        case 53:
#line 135 "loxgram"
        { d_val_ = std::make_shared<ExprUnary>(MINUS, std::dynamic_pointer_cast<Expr>(vs_(0))); }
        break;

        case 54:
#line 138 "loxgram"
        { d_val_ = std::make_shared<ExprBinary>(EQUAL_EQUAL, std::dynamic_pointer_cast<Expr>(vs_(-2)), std::dynamic_pointer_cast<Expr>(vs_(0))); }
        break;

        case 55:
#line 139 "loxgram"
        { d_val_ = std::make_shared<ExprBinary>(BANG_EQUAL, std::dynamic_pointer_cast<Expr>(vs_(-2)), std::dynamic_pointer_cast<Expr>(vs_(0))); }
        break;

        case 56:
#line 140 "loxgram"
        { d_val_ = std::make_shared<ExprBinary>(LESS, std::dynamic_pointer_cast<Expr>(vs_(-2)), std::dynamic_pointer_cast<Expr>(vs_(0))); }
        break;

        case 57:
#line 141 "loxgram"
        { d_val_ = std::make_shared<ExprBinary>(LESS_EQUAL, std::dynamic_pointer_cast<Expr>(vs_(-2)), std::dynamic_pointer_cast<Expr>(vs_(0))); }
        break;

        case 58:
#line 142 "loxgram"
        { d_val_ = std::make_shared<ExprBinary>(GREATER, std::dynamic_pointer_cast<Expr>(vs_(-2)), std::dynamic_pointer_cast<Expr>(vs_(0))); }
        break;

        case 59:
#line 143 "loxgram"
        { d_val_ = std::make_shared<ExprBinary>(GREATER_EQUAL, std::dynamic_pointer_cast<Expr>(vs_(-2)), std::dynamic_pointer_cast<Expr>(vs_(0))); }
        break;

        case 60:
#line 144 "loxgram"
        { d_val_ = std::make_shared<ExprBinary>(PLUS, std::dynamic_pointer_cast<Expr>(vs_(-2)), std::dynamic_pointer_cast<Expr>(vs_(0))); }
        break;

        case 61:
#line 145 "loxgram"
        { d_val_ = std::make_shared<ExprBinary>(MINUS, std::dynamic_pointer_cast<Expr>(vs_(-2)), std::dynamic_pointer_cast<Expr>(vs_(0))); }
        break;

        case 62:
#line 146 "loxgram"
        { d_val_ = std::make_shared<ExprBinary>(STAR, std::dynamic_pointer_cast<Expr>(vs_(-2)), std::dynamic_pointer_cast<Expr>(vs_(0))); }
        break;

        case 63:
#line 147 "loxgram"
        { d_val_ = std::make_shared<ExprBinary>(SLASH, std::dynamic_pointer_cast<Expr>(vs_(-2)), std::dynamic_pointer_cast<Expr>(vs_(0))); }
        break;

        case 64:
#line 150 "loxgram"
        { d_val_ = std::make_shared<ExprLogical>(OR, std::dynamic_pointer_cast<Expr>(vs_(-2)), std::dynamic_pointer_cast<Expr>(vs_(0))); }
        break;

        case 65:
#line 151 "loxgram"
        { d_val_ = std::make_shared<ExprLogical>(AND, std::dynamic_pointer_cast<Expr>(vs_(-2)), std::dynamic_pointer_cast<Expr>(vs_(0))); }
        break;

        case 66:
#line 154 "loxgram"
        { d_val_ = std::make_shared<ExprVariable>(get<std::string>(std::dynamic_pointer_cast<ExprLiteral>(vs_(0))->get())); }
        break;

        case 67:
#line 155 "loxgram"
        { d_val_ = std::make_shared<ExprLiteral>(std::stod(scanner.matched())); }
        break;

        case 68:
#line 156 "loxgram"
        { d_val_ = std::make_shared<ExprLiteral>(scanner.matched().substr(1, scanner.matched().size() - 2)); }
        break;

        case 69:
#line 157 "loxgram"
        { d_val_ = std::make_shared<ExprLiteral>(true); }
        break;

        case 70:
#line 158 "loxgram"
        { d_val_ = std::make_shared<ExprLiteral>(false); }
        break;

        case 71:
#line 159 "loxgram"
        { d_val_ = std::make_shared<ExprLiteral>(std::monostate{}); }
        break;

        case 72:
#line 160 "loxgram"
        { d_val_ = std::make_shared<ExprGrouping>(std::dynamic_pointer_cast<Expr>(vs_(-1))); }
        break;

        case 73:
#line 161 "loxgram"
        { d_val_ = std::make_shared<ExprThis>(); }
        break;

        case 74:
#line 162 "loxgram"
        { d_val_ = std::make_shared<ExprSuper>(get<std::string>(std::dynamic_pointer_cast<ExprLiteral>(vs_(0))->get())); }
        break;

        case 75:
#line 165 "loxgram"
        { d_val_ = std::make_shared<ExprLiteral>(scanner.matched()); }
        break;

        case 76:
#line 168 "loxgram"
        { d_val_ = vs_(0); }
        break;

        case 77:
#line 171 "loxgram"
        { d_val_ = std::make_shared<ExprCall>(); }
        break;

        case 78:
#line 173 "loxgram"
        {
            d_val_ = vs_(0);
        }
        break;

        case 79:
#line 175 "loxgram"
        { d_val_ = vs_(-2); std::dynamic_pointer_cast<ExprCall>(d_val_)->appendArg(std::dynamic_pointer_cast<Expr>(vs_(0))); }
        break;

        case 80:
#line 176 "loxgram"
        { d_val_ = std::make_shared<ExprCall>(); std::dynamic_pointer_cast<ExprCall>(d_val_)->appendArg(std::dynamic_pointer_cast<Expr>(vs_(0))); }
        break;

        case 81:
#line 179 "loxgram"
        { d_val_ = std::make_shared<ExprGet>(std::dynamic_pointer_cast<Expr>(vs_(-2)), get<std::string>(std::dynamic_pointer_cast<ExprLiteral>(vs_(0))->get())); }
        break;

        case 82:
#line 180 "loxgram"
        { d_val_ = std::dynamic_pointer_cast<ExprCall>(vs_(-1)); std::dynamic_pointer_cast<ExprCall>(d_val_)->setCallee(std::dynamic_pointer_cast<Expr>(vs_(-3))); }
        break;

        case 83:
#line 181 "loxgram"
        { d_val_ = std::make_shared<ExprGet>(std::dynamic_pointer_cast<Expr>(vs_(-2)), get<std::string>(std::dynamic_pointer_cast<ExprLiteral>(vs_(0))->get())); }
        break;

        case 84:
#line 182 "loxgram"
        { d_val_ = std::dynamic_pointer_cast<ExprCall>(vs_(-1)); std::dynamic_pointer_cast<ExprCall>(d_val_)->setCallee(std::dynamic_pointer_cast<Expr>(vs_(-3))); }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler(exc);
}

// derived/nextcycle
void Loxgram::nextCycle_()
try
{
    if (s_state[state_()]->d_type & REQ_TOKEN)
        nextToken_();              // obtain next token


    int action = lookup_();        // lookup d_token in d_state

    if (action > 0)                 // SHIFT: push a new state
    {
        shift_(action);
        return;
    }

    if (action < 0)            // REDUCE: execute and pop.
    {

        if (recovery_())
            redoToken_();
        else
            executeAction_(-action);
                                            // next token is the rule's LHS
        reduce_(-action); 
        return;
    }

    if (recovery_())
        ABORT();
    else 
        ACCEPT();
}
catch (ErrorRecovery_)
{
    if (not recovery_())
        errorRecovery_();
    else
    {
        if (token_() == Reserved_::EOF_)
            ABORT();
        popToken_();               // skip the failing token
    }
}


// derived/nexttoken
void Loxgram::nextToken_()
{ 
    // If d_token is Reserved_::UNDETERMINED_ then if savedToken_() is
    // Reserved_::UNDETERMINED_ another token is obtained from lex(). Then
    // savedToken_() is assigned to d_token.

                                    // no need for a token: got one already
    if (token_() != Reserved_::UNDETERMINED_) 
    {
        return;                             
    }

    if (savedToken_() != Reserved_::UNDETERMINED_)
    {
        popToken_();               // consume pending token
    }
    else
    {
        ++d_acceptedTokens_;       // accept another token (see
                                    // errorRecover())
        lex_(lex());
        print_();
    }
    print();
}

// derived/print
void Loxgram::print_()
{
// $insert print
}

// derived/parse
int Loxgram::parse()
try 
{
    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and all relevant variables
    // are initialized by Base::clearin_.
    //
    // Then, in an eternal loop:
    //
    //  1. If a state is a REQ_TOKEN type, then the next token is obtained
    //     from nextToken().  This may very well be the currently available
    //     token. When retrieving a terminal token d_terminal is set to true.
    //
    //  2. lookup() is called, d_token is looked up in the current state's
    //     SR_ array.
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token is not found, and the state has no
    //     default reduction.

    clearin_();                            // initialize, push(0)

    while (true)
    {
// $insert prompt
        nextCycle_();
    }
}
catch (Return_ retValue)
{
    return retValue or d_nErrors_;
}


// derived/tail


