// Generated by Bisonc++ V6.05.00 on Wed, 31 Jan 2024 14:42:32 +0000

// hdr/includes
#ifndef ParseBase_h_included
#define ParseBase_h_included

#include <exception>
#include <vector>
#include <iostream>
// $insert preincludes
#include "Includes.h"
#include "Tokens.h"

// hdr/baseclass

namespace // anonymous
{
    struct PI_;
}



// $insert parserbase
class ParseBase: public Tokens
{
    public:
        enum DebugMode_
        {
            OFF           = 0,
            ON            = 1 << 0,
            ACTIONCASES   = 1 << 1
        };

// $insert tokens
// $insert STYPE
using STYPE_ = std::shared_ptr<SType>;


    private:
                        // state  semval
        using StatePair = std::pair<size_t, STYPE_>;
                       // token   semval
        using TokenPair = std::pair<int,    STYPE_>;

        int d_stackIdx = -1;
        std::vector<StatePair> d_stateStack;
        StatePair  *d_vsp = 0;       // points to the topmost value stack
        size_t      d_state = 0;

        TokenPair   d_next;
        int         d_token;

        bool        d_terminalToken = false;
        bool        d_recovery = false;


    protected:
        enum Return_
        {
            PARSE_ACCEPT_ = 0,   // values used as parse()'s return values
            PARSE_ABORT_  = 1
        };
        enum ErrorRecovery_
        {
            UNEXPECTED_TOKEN_,
        };

        bool        d_actionCases_ = false;    // set by options/directives
        bool        d_debug_ = true;
        size_t      d_requiredTokens_;
        size_t      d_nErrors_;                // initialized by clearin()
        size_t      d_acceptedTokens_;
        STYPE_     d_val_;


        ParseBase();

        void ABORT() const;
        void ACCEPT() const;
        void ERROR() const;

        STYPE_ &vs_(int idx);             // value stack element idx 
        int  lookup_() const;
        int  savedToken_() const;
        int  token_() const;
        size_t stackSize_() const;
        size_t state_() const;
        size_t top_() const;
        void clearin_();
        void errorVerbose_();
        void lex_(int token);
        void popToken_();
        void pop_(size_t count = 1);
        void pushToken_(int token);
        void push_(size_t nextState);
        void redoToken_();
        bool recovery_() const;
        void reduce_(int rule);
        void shift_(int state);
        void startRecovery_();

    public:
        void setDebug(bool mode);
        void setDebug(DebugMode_ mode);
}; 

// hdr/abort
inline void ParseBase::ABORT() const
{
    throw PARSE_ABORT_;
}

// hdr/accept
inline void ParseBase::ACCEPT() const
{
    throw PARSE_ACCEPT_;
}


// hdr/error
inline void ParseBase::ERROR() const
{
    throw UNEXPECTED_TOKEN_;
}

// hdr/savedtoken
inline int ParseBase::savedToken_() const
{
    return d_next.first;
}

// hdr/opbitand
inline ParseBase::DebugMode_ operator&(ParseBase::DebugMode_ lhs,
                                     ParseBase::DebugMode_ rhs)
{
    return static_cast<ParseBase::DebugMode_>(
            static_cast<int>(lhs) & rhs);
}

// hdr/opbitor
inline ParseBase::DebugMode_ operator|(ParseBase::DebugMode_ lhs, 
                                     ParseBase::DebugMode_ rhs)
{
    return static_cast<ParseBase::DebugMode_>(static_cast<int>(lhs) | rhs);
};

// hdr/recovery
inline bool ParseBase::recovery_() const
{
    return d_recovery;
}

// hdr/stacksize
inline size_t ParseBase::stackSize_() const
{
    return d_stackIdx + 1;
}

// hdr/state
inline size_t ParseBase::state_() const
{
    return d_state;
}

// hdr/token
inline int ParseBase::token_() const
{
    return d_token;
}

// hdr/vs
inline ParseBase::STYPE_ &ParseBase::vs_(int idx) 
{
    return (d_vsp + idx)->second;
}



#endif



